### ISSUE TITLE
push 0.0.2-snapshot to clojars?

### ISSUE THREAD

**Issue by Quantisan** [mikera/core.matrix#10]
Clatrix now has the basic protocols implemented, but we need matrix-api snapshot in clojars to pass travis test

Here's the branch of Clatrix
https://github.com/tel/clatrix/tree/matrix-api

**Comment by mikera** [comment]
Awesome, great stuff Paul. I'm keen to try it out!

I just pushed the latest snapshot out to Clojars as 0.0.2

Obviously still more of a experimental dev snapshot than an actual release, but hopefully that make things work for the Clatrix build at least!
