### ISSUE TITLE
Dataset types

### ISSUE THREAD

**Issue by mikera** [mikera/core.matrix#100]
It would make sense to have a Dataset type object implementation, similar to Incanter.

Proposed features:
- Works as a general purpose array
- Ability to give column names
- Behaves like a matrix, with each column as a vector
- Each column may have different types

This would ideally be supported by a few extra protocols, so that the same dataset protocols can be extended to other types (e.g. Database result sets, Incanter datasets)

**Comment by mikera** [comment]
There's an initial implementation here (still experimental):

https://github.com/mikera/core.matrix/blob/develop/src/main/clojure/clojure/core/matrix/impl/dataset.clj

**Comment by mikera** [comment]
Remaining tasks:
- complete more of the relevant protocols
- API functions for column names etc.

**Comment by mikera** [comment]
@Gerrrr are you going to this issue on as part of the Incanter integration work?

**Comment by Gerrrr** [comment]
Yes, I am currently working on it.

**Comment by mikera** [comment]
Dataset support now exists, so closing this issue
