### ISSUE TITLE
Implementing non-zero-indices

### ISSUE THREAD

**Issue by prasant94** [mikera/core.matrix#108]
```
"Gets the non-zero indices of an array.
   - For a 1D vector, returns an ordered index list.
   - For a higher dimensional array, returns the non-zero-indices for each slice in row-major order."
```

This is the function I wrote:

``` clojure
(defn non-zero-indices [m]
  (if (mp/is-vector? m)                 ; if m is 1D array
    (vec (for [i (range (mp/dimension-count m 0))
                 :when (not (== 0 (mp/get-1d m i)))] 
            i))
    (vec (for [i (range (mp/dimension-count m 0))]
            (non-zero-indices (m i))))))
```

These are the test inputs I ran and their outputs, please check if this is the behavior you expect :

1) `[0]` -> `[]`
2) `[1]` -> `[0]`
3) `[1 0 0 2 5 0]` -> `[0 3 4]`
4) `[[[1.0]][[0]][[9.0]][[0]]]` -> `[[[0]] [[]] [[0]] [[]]]` 
5) `[[[0.0 2.0][0 4.0]][[5.0 6.0][7.0 0]][[9.0 10.0][11.0 12.0]]]` -> `[[[1] [1]] [[0 1] [0]] [[0 1] [0 1]]]`

**Comment by mikera** [comment]
Hi Prasant, this looks like exactly the right kind of behaviour!

Ideally the implementation would go via a protocol, so that implementations can provide a more efficient approach if they have one.
