### ISSUE TITLE
Operations taking 2 sparse vectors (matrices, etc.) return a dense result. 

### ISSUE THREAD

**Issue by michaelochurch** [mikera/core.matrix#115]
I've been looking into the new sparse features and found that, for many of the element-size vector matrix operations that could return sparse, they return dense matrices even when both operands are sparse, like so:

Here's a REPL transcript of this issue:

``` clojure
user> (use 'clojure.core.matrix)
user> (use 'clojure.core.matrix.operators)
user> (set-current-implementation :vectorz)
user> (def v (sparse [1 0 0 0 0 0 0 1]))
user> v  ;; will be sparse
#<SparseIndexedVector [1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0]>
user> (+ v v)
#<Vector [2.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0]> ;; dense return
```

This makes it hard to use sparse vectors using the core.matrix API, because they are cast to dense ones as soon as you do any operations with them.

**Comment by mikera** [comment]
Yes this is a known problem that needs some work.

Basically, it's due to the fact that vectorz-clj isn't yet quite smart enough about what sort of return type it produces. It's really a vectorz-clj issue rather than a core.matrix issue. I'll open an issue there and close this one.

**Comment by mikera** [comment]
https://github.com/mikera/vectorz-clj/issues/18
