### ISSUE TITLE
Possible: Rename dimensionality to size

### ISSUE THREAD

**Issue by ejackson** [mikera/core.matrix#12]
This is a more common name, and shorter !  Rename it ?

https://github.com/mikera/matrix-api/blob/master/src/main/clojure/core/matrix.clj#L78

**Comment by mikera** [comment]
Do you mean `dimensionality` or `dimensions`?

For a 3x3 matrix, dimensionality is 2 (it's a 2D matrix) and dimensions are [3 3]

Apart from that I like the word size in principle but the only main I was cautious about size was ambiguity: it might get confused with the total number of items in the matrix. That it what it means in NumPy at least.....

Any examples of what other matrix libraries use?

**Comment by ejackson** [comment]
Sorry, yes, I mean dimensions.  For this R uses dim, MATLAB uses size, mathematica uses Dimensions.  So no consensus there :)

For the total number of elements matlab provides numel (i think its a bit ugly).  How about count, or card ?

**Comment by mjwillson** [comment]
numpy uses "ndim" for the number of array dimensions, and "shape" for the tuple of sizes along those dimensions.

It also uses the term "axis" a lot in its API for a specific dimension of an ndarray

**Comment by mikera** [comment]
I quite like "shape" as an alternative to "dimensions"

`ecount` might be good as a reasonably concise term for the total number of elements - it would be consistent with `ereduce`, `emap` etc, for the other element-by-element operations.

`ndim` feels unidiomatic to me in Clojure for some reason. Though I recognise I have a general bias against use of abbreviations....

**Comment by ejackson** [comment]
Yes, shape is nice, sounds like quorum to me :)

ecount I think is a problem.  The e_verb_ convention is to apply _verb_ to each element of the matrix, thus wouldn't ecount imply: apply the function count to each element ?  The count we want is not an elementwise op, but a collectionwise op.  Admittedly, this might be inferring too much from the convention.

I still think count or card are better.

**Comment by mikera** [comment]
OK sounds agreed dimensions -> shape

OTOH I don't think `e*verb*` does currently mean apply `*verb*` to each element at present - `ereduce` for example isn't applying `reduce` to each element, it is applying `reduce` to a hypothetical sequence of all elements. Likewise for `emap`. `e+` works as shorthand for `emap +` in this sense.

`ecount` would be consistent with that, the sense that `(count seq)` returns the count of all elements in a seq.  

Without having a specific formal definition in mind, I was interpreting e_something_ as "version of `something` that works over the array seen as a collection of elements". Rather like `areduce` for Java arrays in clojure.core. I imagine clojure.core would have `acount` as well were it not for the fact that `count` already works fine on Java arrays.

This is good discussion though - let's keep pushing this, naming is so important for any API.

**Comment by mikera** [comment]
Anyone want to do a patch for dimensions -> shape?

Happy to do it myself, but I'm conscious that other people may want to get involved with hacking the API and this is probably a good one to start with.....

**Comment by ejackson** [comment]
e_verb_.  I see your point.   I need to think about this a bit.

**Comment by mikera** [comment]
Seems like we can close this one.
