### ISSUE TITLE
Implement test.check matrix generators

### ISSUE THREAD

**Issue by mikera** [mikera/core.matrix#120]
It would be useful to have valid test.check generators to produce arbitrary arrays for generative testing of core.matrix and its implementations.

Key features required:
- Generate arrays from different implementations
- Generate arrays with randomised dimensionality / shape
- Generate randomised values based on the element type of the array
- Control the size of generated arrays (so that tests run in reasonable time) - this is important because adding dimensions may cause exponential growth in array size :-)
- Generation of arrays using different operations like sub-matrices, joining of smaller arrays etc.

**Comment by mschuene** [comment]
see https://github.com/mikera/core.matrix/pull/122
