### ISSUE TITLE
conforming? bug or irritating documentation

### ISSUE THREAD

**Issue by mschuene** [mikera/core.matrix#126]
From its documentation, conforming? seems to imply that if 
(conforming? a b)
(add a b) 
is possible. However, that is not the case
(conforming? [0.0 0.0] [[0.0]]) ;=> true
(add [0.0 0.0] [[0.0]]) ;=> RuntimeException Incompatible shapes, cannot broadcast [2] to [1 1]  clojure.core.matrix.impl.persistent-vector/eval5394/fn--5395 (persistent_vector.clj:156)

**Comment by mikera** [comment]
That looks like a conforming bug to me. No way can those two arrays be considered to conform!

**Comment by mschuene** [comment]
From the description about implicit broadcasting on the wiki, this should fix it:
https://github.com/mikera/core.matrix/pull/127

**Comment by mikera** [comment]
Fixed now I think
