### ISSUE TITLE
Parallel Colt

### ISSUE THREAD

**Issue by siscia** [mikera/core.matrix#13]
I tried to make a very first implementation of the matrix of Parallel Colt (PC), however it is a huge mess... I guess I am missing something in the multimethod stuff...

It is not complete https://gist.github.com/4525672

What I noticed is that (PC) does not have a real and clear abstraction of matrix... 

It may be me, but I guess that implement PC is gonna be a big mess...

Cheers

Simone

**Comment by heffalump** [comment]
I started looking at the Parallel Colt Java Doc, and yeah, it does look pretty complicated.  I think we can find the relevant classes for our purposes, though. For instance the abstract base class for a matrix of doubles is cern.colt.matrix.tdouble.DoubleMatrix2D.  What about simply extending our protocols directly onto that class and its cousins?
e.g.

(extend cern.colt.matrix.tdouble.DoubleMatrix2D
  PImplementation
   ....
  PAnotherProtocol
   ....
)

And then we want to make sure that we have closure around the universe of types to which we have extended our protocols.  It may turn out that we don't even want or need to extend our protocols to all of the matrix types that PColt has.

I don't think that we need or want multimethods here (though I haven't actually done the implementation, so I may be wrong).

**Comment by siscia** [comment]
> What about simply extending our protocols directly onto that class and its cousins?

Yeah, I believe that is the better way... 
We should write something really cool that does not force us to write the same code for very similar class...
I don't have too much experience, I will try to work on it...

**Comment by mikera** [comment]
I think extending protocols onto Parralel Colt abstract classes like @Heffalump suggests is the right way to go.

It's mildly annoying that PC has different parallel hierarchies for different data types (e.g. IntMatrix2D vs DoubleMatrix2D). 

I suspect DoubleMatrixXD are the ones that will be most useful, but the thought occurs to me that it might be possible to use Clojure macros to extend the relevant protocols to the other types as well. This might get a bit complex if there are special cases for the different types but I think it is feasible and it might the best way to go if we want to support _all_ the Parallel Colt types. Konread Hinsen used a similar technique to support different array types in his clj-multiarray work, see e.g.:
- http://code.google.com/p/clj-multiarray/source/browse/src/multiarray/type.clj

Perhaps start with the DoubleMatrixXD classes, but write it in a way that it could be turned into a more general macro later if needed?

**Comment by siscia** [comment]
Sometimes before to work is necessary to be sure if we are using our resource in a good way.

It is PC the fastest implementation of matrix we have in the java world ?
It is the best to do something specific ?
Why we want to implement the PC ?

We want to define the standard abstraction for matrix in the clojure world, should be matter how this is implemented?
I believe it should not be matter as long as we make possible to have a standard representation of matrix (vector of vector ?)  that everybody can take and convert in his specific type to use in their old platform (it is clear ?)

What should be matter for us is to give a standard implementation, as fast as possible (reducers ???).
However in the early stage is necessary to realized the standard and don't care too much of the velocity, it would be early optimization, only when everything is stable we should thing how make it fast.

(I might have lost something, but do we want to be concentrated on only the numerical side of matrix, or we care also to memorize object ?)

Simone Mosciatti

**Comment by heffalump** [comment]
I'm not looking at benchmarks right now, but I believe that Parallel Colt is quite good.  (JBlas might be faster for many operations, but there are many things that JBlas hasn't implemented.)

But we're not really worried about whether one implementation is the best.  As I understand the plan, it's to provide a convenient interface to several leading java implementations and let the user select which one he or she wishes to use.  (As well as, of course, having the internal implementations which don't depend on any external libraries.)

But Parallel Colt is quite complicated in its class structure.  To go to the other extreme, JAMA http://math.nist.gov/javanumerics/jama/ would be much easier to start with.)

**Comment by siscia** [comment]
Benchmarks here: http://code.google.com/p/java-matrix-benchmark/
I didn't do it, I just find it mentioned here: http://stackoverflow.com/questions/529457/performance-of-java-matrix-math-libraries 
I guess we can trust those benchmarks.

>  As I understand the plan, it's to provide a convenient interface to several leading java implementations and let the user select which one he or she wishes to use.

I understood in a different way, as I got it we want to create a common abstraction for matrix, so if I want a matrix in clojure I will just type (matrix something) and I will get my ready-to-go battery-included matrix, then if I need a boost in performance I may want to define what implementation I wish to use so that everything will go faster, same deal if I want a particular function (???) that only one libraries provide.
It is probably me getting something wrong.

Little note on performance, we are an hosted language, I don't think there is any way to consistently go faster than the implementation we use under the hood. The only thing we can do, is to use parallel and concurrent tools (reducers, amap, etc) we might want to thing about this during our implementation, even if it could be early-optimization that we really need to avoid.

PS: Someone (probably I) get confused about what we really want from this library, I guess is necessary to modify the README of the project...

**Comment by mikera** [comment]
@sisca -  I think you've got it exactly right.

We want to make it easy for people to get a powerful and fast "batteries included" matrix in Clojure, without having to be tied to a specific underlying implementation. And we certainly want to be able to construct matrices easily with something like:

``` clojure
(matrix [[1 0] [0 1]])
```

Parallel Colt seems a good choice for such an underlying implementation, but there are also other good options. In the long run, the more implementations we have the better.

**Comment by mjwillson** [comment]
@sisca: I'm not sure I agree with this though:

> However in the early stage is necessary to realized the standard and don't care too much of the velocity, it would be early optimization, only when everything is stable we should thing how make it fast.

Most use cases for computational linear algebra are performance-sensitive. For quite a lot of them it's the main performance bottleneck.

If the goal is for this to be more than a toy, we need to _think_, at least, about what is necessary in the API to support existing fast matrix implementations, right from the start. And we should certainly look to have integrated one (ideally more than one) of them before calling the API stable.

If we wait until the API is stable before thinking about supporting fast implementations, it could be too late to make necessary changes.

-Matt

**Comment by siscia** [comment]
> If the goal is for this to be more than a toy, we need to _think_, at least, about what is necessary in the API to support existing fast matrix implementations, right from the start. And we should certainly look to have integrated one (ideally more than one) of them before calling the API stable.

I agree, I thought to have express it somewhere, it has to be my fault.

What I think is that we need to have a stable API and implementation like first think, then we think to make it fast.
Of course since we already know that this lib is gonna be fast we all need to think about when we are implement stuff.

A little thought, do we really want mutable structures ?
Are they gonna work fine with the reducers ?
I am not so sure, but really don't know. (I am not even sure that we are gonna use reducers but it looks like the most obvious way for me...)

We are a little OT, don't we ?

**Comment by mikera** [comment]
This kind of open discussion is probably best for the discussion group:
- https://groups.google.com/forum/#!forum/numerical-clojure

I'll close this issue as it doesn't actually seem to be an issue - we can continue the discussion on the discussion group if needed.
