### ISSUE TITLE
Add API functions for standard matrix decompositions

### ISSUE THREAD

**Issue by mikera** [mikera/core.matrix#14]
We should have API functions for most standard matrix decompositions.

In particular we should have:
- LU (lower upper trinagular decomposition)
- SVD (singular value decomposition)
- QR 
- Cholesky distribution
- probably a few others.....

Naming is TDB, we have various proposals:
- `lu`
- `decompose-lu`
- `lu-decompose`
- `decomposition-lu`
- `lu-decomposition`

Need to decide on a consistent and logical naming scheme before we commit to a public API.

Also need to define return values. Current thinking is a map (or defrecord?) that contains clearly labeller values e.g.

```
(decompose-lu matrix)
=> {lower: [matrix1]
      :upper: [matrix 2]
      :determinant [double value]
```

See:
- https://groups.google.com/forum/?fromgroups=#!topic/numerical-clojure/DN8aD__q5BU

**Comment by ejackson** [comment]
I vote for short names: ld, svd, qr etc.

**Comment by mikera** [comment]
I'm more in favour of being a bit more explicit:

``` clojure
lu-decomposition
```

It's a close call I admit. But see my reasoning in the newsgroup:
- https://groups.google.com/d/msg/numerical-clojure/DN8aD__q5BU/0_vc3uwRtdIJ

**Comment by mikera** [comment]
Closing this as now complete.

Opted for the longer names so we can do stuff like:

``` clojure
(let [qr (qr-decomposition m)]
  .... do stuff with qr)
```
