### ISSUE TITLE
bug in ndarray as-vector

### ISSUE THREAD

**Issue by mschuene** [mikera/core.matrix#141]
(as-vector (matrix :ndarray [[1 2][3 4]])) ;=> nil
(as-vector (matrix :persistent-vector [[1 2][3 4]])) ;=> [1 2 3 4]

**Comment by mikera** [comment]
Not strictly a bug. The documentation says as-vector may return nil if it doesn't support vector views.

`to-vector` should be used instead if you want a flattened vector and don't care about getting a mutable view or not.
