### ISSUE TITLE
Bug in ndarray transpose! for large matrices

### ISSUE THREAD

**Issue by mschuene** [mikera/core.matrix#142]
for small matrices, transpose! works fine, but
(transpose! (matrix :ndarray (partition 100 (range 100000))))
;=>ArrayIndexOutOfBoundsException 100000  clojure.lang.RT.aget (RT.java:2238)

**Comment by mikera** [comment]
That's not a square matrix - so I'm not particularly surprised that the in-place `transpose!` operation fails. 

Perhaps you should try `transpose` instead :-)

The error message should certainly be improved though!

**Comment by mschuene** [comment]
Oh yes, I mistakenly assumed that when transpose works, transpose! should
also work
