### ISSUE TITLE
Pretty-printing for matrices

### ISSUE THREAD

**Issue by mikera** [mikera/core.matrix#15]
Should have a pretty-printer for matrix output, allowing at least the following:
- Alignment of columns/ decimal places
- Truncation of double values to a fixed number of decimal places
- Max size truncation for very large matrices (maybe display 20x20 max by default?)

Printed output should still be readable clojure data.

Output might be something like:

``` clojure
[[-1.000  0.000  0.000]
 [ 0.000  3.141  0.000]
 [ 0.000  0.000 -2.718]]

```

**Comment by grtlr** [comment]
I'm quite new to programming in clojure, so I figured that this might be a good exercise. I forked your repository to work on that.

**Comment by mikera** [comment]
Great stuff - I think I created a `pm` stub in clojure/core/matrix.clj that you may want to build onto.

Let me know if you run into any issues / queries!

**Comment by mikera** [comment]
Seems to be working now for the basic cases quite well. 

Appears to need extending still to support the general case N-dimensional arrays

**Comment by mikera** [comment]
Closed this as the basic implementation is now in place. Have opened a separate issue for N-dimensional support
