### ISSUE TITLE
how can i multiple two matrix use clojure.core.matrix.operators/*

### ISSUE THREAD

**Issue by zjhsdtc** [mikera/core.matrix#167]
after execute code below

``` clojure
(:require [clojure.core.matrix.operators :as M]) 
(:use clojure.core.matrix)

(def mat-a (matrix [[1 2 3] [4 5 6]]))
(def mat-b (matrix [[10 20] [20 30] [30 40]]))
(mmul mat-a mat-b) ;;this code works fine
(M/* mat-a mat-b) ;;error with this code
```

error occurred that

``` shell
java.lang.RuntimeException: Incompatible shapes, cannot broadcast [3 2] to [2 3]
 at clojure.core.matrix.impl.persistent_vector$eval5053$fn__5054.invoke (persistent_vector.clj:156
```

i read the source code and find that clojure.core.matrix.operators/\* is just alias of clojure.core.matrix/mul, so how can i multiply two matrix use clojure.core.matrix/mul or i only can multiply matrix use clojure.core.matrix/mmul?

**Comment by Gerrrr** [comment]
Hi,
`clojure.core.matrix/mul` is an element-wise multiplication while `clojure.core.matrix/mmul` is a matrix multiplication.
If you want to perform matrix multiplication, you should use `clojure.core.matrix/mmul`.

**Comment by zjhsdtc** [comment]
ok thx i got it :)
