### ISSUE TITLE
Dataset construction from sequences of maps

### ISSUE THREAD

**Issue by mikera** [mikera/core.matrix#174]
Sequences of maps are quite a common data format (e.g. this is produced by clojure.java.jdbc). It would be good to support easy construction of datasets using this kind of input.

``` clojure
(dataset-from-maps [{:a 1 :b 2} {:a 1 :b 2} {:a 2 :b 10}])
=> <corresponding DataSet>
```

**Comment by mikera** [comment]
@Gerrrr might be one for you to think about in your DataSet support for Incanter? I spotted this as a potentially useful feature today while working with `clojure.java.jdbc`

**Comment by mikera** [comment]
Some other ideas:
- Could be a 1-arity overload of the current `dataset` constructor function
- Could also support sequences vectors (considering 0,1,2 .... as keys)

**Comment by alexott** [comment]
`to-dataset` function in `incanter.core`  right now supports such conversion -> could be taken from Incanter

**Comment by Gerrrr** [comment]
I see 4 possible arguments from which  `DataSet` can be created:
1. column names and `seq` of columns
2. matrix -  (column names will be `0,1,2,3,...`)
3. map `{colname [col vals]}`
4. vector `[{colname1 val1, colname2 val2}]`

I propose to define function `(dataset column-names columns)`, which creates dataset as described in 1. and `(dataset m)` which will be dispatched by argument type - matrix, map, vector of maps.

**Comment by mikera** [comment]
Sounds sensible. Might have to be clear about testing order to resolve ambiguity.... remember that a vector of vectors counts as a matrix, for example.....

4 presumably apples to any seqence or seqable thing that isn't one of the others.... right? And presumably any `associative?` type would work for the inner elements?

**Comment by Gerrrr** [comment]
> 4 presumably apples to any seqence or seqable thing that isn't one of the others.... right? And presumably any associative? type would work for the inner elements?

Yes, of course.

**Comment by mikera** [comment]
@Gerrrr think this is all done now - OK to close?

**Comment by mikera** [comment]
Closing because it all seems to be working fine:

``` clojure
 (dataset [{:a 1 :b 2} {:a 1 :b 2} {:a 2 :b 10}])
#clojure.core.matrix.impl.dataset.DataSet{:column-names [:a :b], :columns [[1 1 2] [2 2 10]]}
```
