### ISSUE TITLE
What does 'pre-scale' mean as opposed to 'scale'?

### ISSUE THREAD

**Issue by mjwillson** [mikera/core.matrix#19]
Bit confused about this.

``` clojure
(defprotocol PMatrixScaling
  "Protocol to support matrix scaling by scalar values"
  (scale [m a])
  (pre-scale [m a]))
```

Surely pre- and post-multiplication by a scalar are the same thing (just element-wise scaling)? Or did you have something else in mind?

**Comment by mjwillson** [comment]
I guess if you want to allow scalars from a non-commutative ring -- although I wonder what consequences that would have for the rest of the API?

**Comment by mjwillson** [comment]
Ah, perhaps you meant something more like multiplication by a diagonal matrix (so potentially scaling by a different factor for each row/column) and `a` is a vector? perhaps best to be clear about it if this is the case. (Note this could also be achieved via a broadcasted element-wise multiplication.)

**Comment by mikera** [comment]
It's for non-commutative stuff like complex scalars if we ever decide to support these

Just thinking ahead :-)

**Comment by mikera** [comment]
For any normal commutative scalars, it means the same as scale.

**Comment by heffalump** [comment]
But complex numbers commute under multiplication.

**Comment by mikera** [comment]
Sorry I meant quaternions :-)

**Comment by mjwillson** [comment]
Ah, gotcha. If we want to do a complete job of supporting non-commutative scalar rings it might have consequences for other parts of the API though, e.g. decompositions -- since this is no longer just plain old linear algebra but module theory in the sense of http://en.wikipedia.org/wiki/Module_(mathematics) . From the little I remember about decomposition theorems for module homomorphisms I'd probably steer well clear :)
