### ISSUE TITLE
Compliance tester and integer implementations

### ISSUE THREAD

**Issue by hokkaido** [mikera/core.matrix#194]
As mentioned in the Numerical Clojure group, at the moment the compliance tester fails when an implementation's element type is an integer (primitive java types such as int or long). There might be something wrong with my implementation, or the compliance tester might be broken.

```
FAIL in (compliance-test-primitives) (compliance_tester.clj:519)
expected: (orthogonal? m4)
  actual: (not (orthogonal? #<MDIntArray MDIntArray({3,3}): {0,0,0,0,0,0,0,0,0}>))

lein test :only clj-hdf5.mdarray-test/compliance-test-primitives

FAIL in (compliance-test-primitives) (compliance_tester.clj:519)
expected: (orthogonal? m4)
  actual: (not (orthogonal? #<MDIntArray MDIntArray({3,3}): {0,0,0,0,0,0,0,0,0}>))

lein test :only clj-hdf5.mdarray-test/compliance-test-primitives


FAIL in (compliance-test-primitives) (compliance_tester.clj:519)
expected: (orthogonal? m4)
  actual: (not (orthogonal? #<MDIntArray MDIntArray({3,3}): {0,0,0,0,0,0,0,0,0}>
))

lein test :only clj-hdf5.mdarray-test/compliance-test-primitives

FAIL in (compliance-test-primitives) (compliance_tester.clj:519)
expected: (orthogonal? m4)
  actual: (not (orthogonal? #<MDIntArray MDIntArray({3,3}): {0,0,0,0,0,0,0,0,0}>))

lein test :only clj-hdf5.mdarray-test/compliance-test-primitives

FAIL in (compliance-test-primitives) (compliance_tester.clj:789)
expected: (equals (shape R) [2 2])
  actual: (not (equals [2 1] [2 2]))

```

**Comment by mikera** [comment]
The final test failure around `shape` makes me suspicious.... if `shape` is broken then `orthogonal?` is pretty likely to fail too, since the default implementation uses `shape`.

@hokkaido Can you check this first and report back?

**Comment by mikera** [comment]
The following works.... so I don't think there is a specific problem with integers....

``` clojure
(orthogonal? [(int-array [0 1]) (int-array [1 0])])
=> true
```

**Comment by mikera** [comment]
@hokkaido - is this fixed now for you? Should I close?

**Comment by hokkaido** [comment]
I haven't solved this yet on my end, but I can reopen if it turns out to be a problem with core.matrix.

**Comment by mikera** [comment]
OK thanks - let me know if you find anything odd!
