### ISSUE TITLE
mux operator

### ISSUE THREAD

**Issue by gtmacdonald** [mikera/core.matrix#195]
Would a mux operator be something useful to add? I'm playing with audio and need to interleave several channels together before sending it to the audio device. At the moment it's only 2; left, and right.

=> (def as [1 2 3])
=> (def bs [4 5 6])
=> (mux as bs)
[1 4 2 5 3 6]

Maybe a mux! version as well. If you would like me to add this let me know. Thx for the great library!

**Comment by mikera** [comment]
I'm a bit hesitant to duplicate the core function `interleave` without a very good reason:

``` clojure
(interleave [1 2 3] [4 5 6])
=> (1 4 2 5 3 6)
```

Now that is a sequence rather than an array result so there could be a performance argument for an array version.... but I'm still not sure if that deserves a place in the core.matrix main API

**Comment by mikera** [comment]
@gtmacdonald I'm thinking you could implement `mux!` quite efficiently using `set-column!` and `as-vector` on a Nx2 matrix , at least for implementations like `vectorz-clj` that support efficient column views.

**Comment by gtmacdonald** [comment]
@mikera I might be putting the horse before the cart here. I'm researching what my options are for fast audio processing but it might not be necessary. Thanks for the feedback. I'll give set-column! a try.

**Comment by mikera** [comment]
To get max performance I think you want:
- `:vectorz` implementation
- Use a Nx2 Matrix class (row major storage)
- Use `set-column!` with the vector of data representing each channel
- Use `as-vector` to convert to a flattened vector at the end

If you do that, there should be zero copying and almost zero new memory allocation (apart from allocating the original Matrix)

**Comment by gtmacdonald** [comment]
Thanks! That sounds good.

**Comment by gtmacdonald** [comment]
Works great!

```
(defn mux
  [a b]
  (let [r (new-matrix frames-per-buffer 2)]
    (set-column! r 0 a)
    (set-column! r 1 b)
    (as-vector r)))
```
