### ISSUE TITLE
Finalise matrix operation function naming

### ISSUE THREAD

**Issue by mikera** [mikera/core.matrix#2]
Need to decide on a consistent function name set for matrix operations.

There seems to be a lot of options, e.g.
- mul (vecmath, jblas, vectorz)
- mult (clatrix, colt)
- multiply (english!)

Tempted to go with mul for consistency with majority of underlying implementations - any better ideas?

Others are probably easier - use the obvious three letter abbreviations if we go with mul
- add
- sub
- div

Maths functions can mimic java.lang.Math like clatrix?
- exp
- log10
- signum
- etc.

Other operations should generally use full english words, especially where they match mathematical terms:
- negate
- determinant
- trace
- etc.

**Comment by ejackson** [comment]
If we're going with 3 letters names I think determinant could be det (following matlab).  How about just log, with an optional argument for the base, and perhaps log2 and log10 ?

Why not use the maths symbols: *, + etc ?  Clatrix does this.  Namespaces should take care of any clashes.  

What about elementwise ops ?  Append an i to everything: muli, expi etc ?

**Comment by mikera** [comment]
I actually created a namespace `core.matrix.operators` that people case use if they want the convenient \* / + / - etc. They fall back intelligently to clojure.core/+ if neither argument is a matrix.

I was thinking the 3-letter versions would just be for the most frequently used and obvious operations (mul, add, sub). I'm indifferent between `det` and `determinant`. Normally I prefer full words for clarity. But I note that mathematical convention also uses `det` frequenty. So lets go with that.

For the "in-place" ops I'm thinking we should follow Clojure convention and use `!` to indicate side effects, e.g. `sin!` to do an in-place sin opertion on a matrix.

On the maths op stuff there is a `log` in fact for base `e` logarithms. I've just followed the convention of the corresponding Java functions, see the map used to generate these:
- https://github.com/mikera/matrix-api/blob/master/src/main/clojure/core/matrix/impl/mathsops.clj

**Comment by ejackson** [comment]
operators: cool, that's nice.
det: cool.

elementwise: I don't mean in place ops, for that I agree that ! is the way forwards, as we did in Clatrix.  I mean elementwise ops, like .\* in matlab, or muli in jblas.

**Comment by ejackson** [comment]
math op link: thank, that's clear.

**Comment by mjwillson** [comment]
I know matlab does it this way, but to me it feels a bit funny to use + for element-wise array version of +, - for the elementwise array version of - etc, but \* for non-elementwise matrix multiplication. Feel like arithmetic ops should translate according to the same rule into things which apply element-wise over arrays, especially in a general NDArray setting. Matrix multiplication is kinda special and different so happy to use (mult) or (mul) for it.

Would definitely prefer to keep these things reasonably concise though -- maths is already pretty verbose when written out as s-expressions :)

**Comment by mikera** [comment]
Hmmm `*` doing matrix multiplication for me satisfied the "principle of least surprise". Element-wise multiplication is (in my experience at least) a relatively rare operation with matrices.

I don't have particularly a strong view on this either way, I'd rather stick with conventions used by other libraries if we can though.

**Comment by heffalump** [comment]
I also like \* for matrix multiplication, because its consistent with what one would expect from linear algebra.  I don't see any contradiction with the addition operator -- that's just how matrix addition is normally defined.  An element-wise multiplication operator .\* might be nice though.

**Comment by mikera** [comment]
`.*` doesn't work in Clojure (conflicts with the syntax for Java method interop).

We could use `*'` perhaps? 

Or `e*` as shorthand for elementwise-multiply?

**Comment by mikera** [comment]
I'm tending towards `e*` unless anyone has a better idea, since it naturally works for a range of other element-wise functions:
- ereduce (reduce over all elements)
- emap (map over all elements)
- esum (sum of all elements)
- etc.

**Comment by mjwillson** [comment]
Re `emap`: clojure.core uses `amap` for mapping over an array, perhaps would be good to be consistent with that if going down the prefix route?  http://clojuredocs.org/clojure_core/1.2.0/clojure.core/amap

> I also like \* for matrix multiplication, because its consistent with what one would expect from linear algebra.

Well to be fair, in linear algebra it's just written just as juxtaposition, if you see a symbol used it's more likely for some other kind of product (tensor, hadamard, ...). Hadamard (elementwise) product is quite useful, any time you want to do a bunch of multiplications in parallel.

I guess it depends if you're looking at this as primarily a more general array programming framework (in which case consistency of how operations which apply over arrays are named would probably take priority, as in e.g. numpy) or primarily as a linear algebra library, in which case I guess matrix multiplication takes precedence.

Bit of a bikeshed discussion I admit, so I'll duck out now :)

**Comment by mikera** [comment]
Closing as I think all points have either been incorporated or moved into other issues.
