### ISSUE TITLE
Broadcasting for element-wise binary operations

### ISSUE THREAD

**Issue by mikera** [mikera/core.matrix#20]
We should have broadcasting support for element-wise binary operations, e.g. matrix addition.

Design principles:
- Should work like NumPy (http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)
- Should preserve fast path when broadcasting is not needed

**Comment by mjwillson** [comment]
Just to clarify, broadcasting is all about element-wise operations, rather than matrix multiplication right?

**Comment by mikera** [comment]
Yes that's right it's for all the element-wise binary operations (which includes element-wise multiplication of course) 

I've updated the issue to reflect this.

**Comment by mikera** [comment]
Have stubbed out a broadcasting protocol in the latest master.

**Comment by mikera** [comment]
0.2.0 has support for explicit broadcasting via `(broadcast matrix target-shape)`
