### ISSUE TITLE
Api suggestion: emap-indexed

### ISSUE THREAD

**Issue by scottdw** [mikera/core.matrix#202]
In using core.matrix for image processing I would find an equivalent of `clojure.core/map-indexed` in core.matrix very useful. If this would be useful more generally please consider adding it to the core.matrix api.

Naive implementation:

``` clojure
(defn emap-indexed [f m]
  (matrix (for [row (range (row-count m))]
            (for [col (range (column-count m))]
              (f col row (mget m col row))))))

(pm (emap-indexed (fn [c r v] (+ c (* r 3))) (matrix (partition 3 (repeat 9 0)))))
;; [[0.000 1.000 2.000]
;;  [3.000 4.000 5.000]
;;  [6.000 7.000 8.000]]
```

**Comment by mikera** [comment]
Good idea! I think we form we would want is to provide the index as a collection. This would enable the components to be accessed via destructuring, something like:

``` clojure
(pm (emap-indexed (fn [[c r] v] (+ c (* r 3))) (matrix (partition 3 (repeat 9 0)))))
```

**Comment by mikera** [comment]
Closing since this is now implemented.
