### ISSUE TITLE
Getting non-zero rows and columns

### ISSUE THREAD

**Issue by drone29a** [mikera/core.matrix#204]
I have code operating on largish (10^4 x 10^4) sparse matrices and occasionally need to process rows or columns. The naïve approach is to use core.matrix/rows or columns, but this ends up creating many empty vectors and adds unnecessary iterations to the row/column processing.

I'm starting work on PNonZeroRows and PNonZeroColumns with non-zero-rows and non-zero-columns, respectively. I plan on adding implementations of both to SparseRowMatrix and SparseColumnMatrix. These would return a map of row/column index to SparseIndexedVector.

Is this an acceptable solution, any suggestions?

Finally, I notice non-zero-indices is not working on sparse matrices. I'll fix this unless you beat me to it, only mentioning in case you're in the middle of a change. It looks like dimension-count in core.matrix.impl.default is called and line 468 attempts to call count on the dimension index and fails.

**Comment by drone29a** [comment]
Looked at this more and implementing those protocols in on top of non-zero-indices is a no go. The current implementation of non-zero-indices (using get-major-slice) would iterate over all the rows in a SparseRowMatrix and negate the benefit of an non-zero-rows function.

Instead we should introduce an index of non empty rows (or columns for SparseColumnMatrix). For any row/column not given non-zero values when initialized or any row/column not set (including get{Row,Column}View which ensure vector is mutable) we assume the row/column is represented by the emptyRow and there is no entry for that row/column in this new index.

We can then base implementations of PNonZeroRows and PNonZeroColumns on this non-sparse-row/column index.

Any thoughts? Please let me know if I'm missing something. In the end this is all about getting non-zero rows and columns as efficiently as possible.

**Comment by drone29a** [comment]
Current plan is to tune SparseRowMatrix. Going to add getRows which uses the data[] array to not make unnecessary getRow calls. Then will add getColumns and getColumn which iterate over all the non-zero values to construct SparseIndexedVector columns.

Then will revisit above comments and select next step.

**Comment by mikera** [comment]
It strikes me as a bit unusual to have matrices with many entire empty rows... are you sure that this is actually the case? This would be an exceptionally sparse matrix...

Either way, `SparseRowMatrix` should use a `ZeroVector` to represent empty rows, so the storage should be minimal and doing `getRow(i).isZero()` will be really cheap so you can probably even afford to check each row in turn. (it should only be O(N) for an N*N matrix in most cases)

**Comment by drone29a** [comment]
There can be zeroed rows when selecting a subset of a documents from a document-term matrix, for example.

**Comment by mikera** [comment]
OK I see. I still think that a `SparseRowMatrix` should be efficient enough. The use of internal ZeroVectors for empty rows is a _really_ nice trick.

**Comment by drone29a** [comment]
Right, I noticed the empty row use in `SparseRowMatrix`. It's already used to represent zeroed rows when accessing via `getRow` and will keep that in `getRows`.

What are the semantics for `getRow`, `getRowView`, `getRowClone`? I understand that views will reference the original structure's data. According to API comments, `getRow` may return a view or not. If `getRow` doesn't return a view is it always equivalent to `getRowClone`?

I.e., should it always be possible to define a matrix class' `getRow` in terms of either `getRowView` or `getRowClone`?

**Comment by mikera** [comment]
`getRow` is intended for the fastest possible read access of the row. This often means a view, but might not be (e.g. getRow on a Matrix33 returns a Vector3).

`getRowView` always has view semantics. Use this if you want to use the view to modify the source matrix.

`getRowClone` always returns a fully mutable copy. Use this if you plan on doing other stuff with the data.

So... they are all subtly different. I've updated the docs to clarify this.

**Comment by drone29a** [comment]
Sorry for the silence. I have some more changes related to sparse matrix performance but need to finish the project I'm using the library for before tidying them up as a pull request. The performance is "good enough" using the Vectorz backend, but I had previously used Colt directly for similar projects and anecdotally obtained better results. I plan to look at the [Java Matrix Benchmark](https://code.google.com/p/java-matrix-benchmark/) and come up with an evaluation of sparse operations.

**Comment by mikera** [comment]
Any performance-enhancing pull requests gratefully received!

The Java Matrix Benchmark only covers dense operations at present, but I could certainly see adding sparse operations. May be useful to note that there is already a GitHub fork of Java-Matrix-Benchmark that includes Vectorz:

https://github.com/prasant94/JavaMatrixBenchmark-for-Vectorz

**Comment by mikera** [comment]
Closing this issue as there don't seem to be any more actions.

Note: there is significantly enhanced sparse matrix support in the latest Vectorz snapshots
