### ISSUE TITLE
Add core.matrix API docs

### ISSUE THREAD

**Issue by danielcompton** [mikera/core.matrix#208]
I looked around and couldn't find generated API docs for core.matrix anywhere. Would it be possible to generate them and host them somewhere? GitHub pages might be a good option. If they do exist then can we add links to them from the README and main wiki page?

**Comment by mikera** [comment]
Sure, I think this would be a good idea. We are currently relying on the docstrings, I agree it would be far better to have proper API documentation.

Any suggestions on tools / approach?

**Comment by danielcompton** [comment]
There's a few options:
- [Codox](https://github.com/weavejester/codox) - most common on 3rd party docs
- [Marginalia](https://github.com/gdeer81/marginalia) - literate programming style
- [Autodoc](https://github.com/tomfaulhaber/autodoc) - used to generate clojure.org docs among others

I lean towards codox personally, and am happy to put together a pull request if you'd like.

**Comment by mikera** [comment]
Codox looks like a decent choice. Happy to have a PR!

Just worth being aware that we use Maven as the main build tool (a Clojure contrib requirement). Presumably we can still make it work.

Also we already have some pages generated for core.matrix (implemntation support matrix etc.)
see e.g. http://mikera.github.io/core.matrix/summary.html

**Comment by danielcompton** [comment]
Hmm, I'll have a look. autodoc is used for contrib projects so maybe it's best to just use that?

**Comment by mikera** [comment]
Not sure. We can use lein to generate docs separately, I guess. It's just a slight pain keeping the pom.xml and project.clj in sync (it would be great if there was a maven plugin that generated the project.clj!)
