### ISSUE TITLE
2D double array

### ISSUE THREAD

**Issue by malloc82** [mikera/core.matrix#214]
I think there is a need to have either a new constructor that can convert a double-array to 2D matrix by supplying row and column or a new to-double-array2 method that can return a 2D double array. 

I was playing with JTransform's FFT library which accept a double array or 2D double array and the result is in the same format. At the moment core.matrix / clatrix can return a double array from a 2D matrix. However, there is no existing API to convert a double array back to the 2D matrix, nor there is a function that can return a 2D double array which existing constructor can accept.

Returning 2D double array should be quite simple, there is existing JBlas API for it.

**Comment by mikera** [comment]
This is a pretty common use case, so happy to have some special support for it.

Though note that it is already possible to coerce a 2D double array into a core.matrix implementation format pretty easily, e.g.

``` clojure
(set-current-implementation :vectorz)

(let [da (into-array (Class/forName "[D") [(double-array [1 2]) (double-array [3 4])])]
     (matrix da))
=> #<Matrix [[1.0,2.0],[3.0,4.0]]>
```

**Comment by mikera** [comment]
Also many of the standard core.matrix functions do work because of sufficiently general default implementations, e.g.

``` clojure
(let [da (into-array (Class/forName "[D") [(double-array [1 2]) (double-array [3 4])])]
     (add da [[1 2] [3 4]]))
=> [[2.0 4.0] [6.0 8.0]]
```

**Comment by malloc82** [comment]
Creating a matrix from 2D array is not an issue, but yielding one. The need for this is this some external library only deal with arrays in either 1D or 2D. In case of 1D, core.matrix need to be able to yield a 1D double array from a matrix and then create a matrix of the same size from a 1D array of the same length; in case of 2D, core.matrix need to be able to yield a 2D double array and create a matrix of the same size from a 2D double array of the same length. In either case, core.matrix at the moment is incomplete, I think, correct me if I'm wrong. Maybe we should have a standard interface in core.matrix for returning 2D array and creating matrix from 1D?

**Comment by malloc82** [comment]
Btw, is there any quick easy way to convert a 1D double array into 2D double array given dimension?

**Comment by malloc82** [comment]
Well, I guess it's probably something like this

``` clojure
(let 
    [da (make-array Double/TYPE row col)]
        (doseq [r row]
            (System/arraycopy origina-array (* r col) (aget da r) 0 col))
    da)
```

**Comment by mikera** [comment]
Ah, if is the `to-double-array` capability that we are looking at then I agree this is probably valuable.

If we are going to do this, might as well do it properly and handle the complete N-dimensional array case (easy enough to do recursively I think....)

**Comment by mikera** [comment]
I have implemented the `clojure.core.matrix.impl.double-array/to-double-arrays` function in latest master

**Comment by malloc82** [comment]
Still, I think a constructor to create a matrix from 1D double array by specifying a row and col without creating a 2D array is very desirable. Depending implementation, unless the data is actually store in 2D array form, convert a 1D array into 2D just to create a matrix seems to be a unnecessary step. This will happen quite frequently when working with external libraries.

**Comment by mikera** [comment]
Yes, though that is implementation specific - Vectorz can do this because it supports a matrix with a 1D backing array for example. 

The other thing you can do is use `reshape` to convert 1D data into a 2D matrix, e.g. 

``` clojure
(reshape [1 2 3 4 5 6 7 8 9] [3 3])
=> [[1 2 3] [4 5 6] [7 8 9]]
```

Do you have any other specific suggestion? Or shall I close this issue?

**Comment by malloc82** [comment]
Ok, I see, it's implementation specific. But since core.matrix is a interface in front of different implementations, should core.matrix provide a interface for that?

**Comment by mikera** [comment]
I think `(reshape (matrix source-array) new-shape)`  should do the job, and it is more general (can support any source and target shape)

No need for a dedicated function just for 2D double arrays, I think.
