### ISSUE TITLE
General API question: submatrix & NDWrapper

### ISSUE THREAD

**Issue by malloc82** [mikera/core.matrix#215]
Just curious, what is the significance of this NDWrapper? Why can't we just return a matrix with the same implementation from the original matrix when calling submatrix? Because it's copying data anyway, so if I want to use the result I have to cast it into matrix which will copy the data array again.

**Comment by mikera** [comment]
NDWrapper has the following properties:
- It avoids copying
- It can work as a view into part of an array that allows modification of the underlying array

In some circumstances this is quite useful, and it serves as a general purpose "default" implementation for submatrix etc. Implementations are free to implement submatrix without using the NDWrapper, of course.

**Comment by malloc82** [comment]
Thanks for the explanation. I do find the submatrix quite useful now since I can pretty much do everything I do matlab easily in clojure with it. But I do have a follow up question/suggestion for it though. 
I find the way of specifying index range, i.e. [start len],  is quite awkward. Matlab and other scientific computation package all use start and end index to specify the range, and it's much easier to read that way too. 
So any chance to add/change support for matlab style of index? Say we can do it like:

``` clojure
(submatrix A [[2 3] [2 4]]) ;; current style
(submatrix A [2 4] [2 5]) ;; matlab style
```

 Also it might be good to add a way to specify the end of row or col, for example, if we want a sub matrix of from second column to the end we can say:

``` clojure
(submatrix A [:] [1 :]) ;; all the rows and all the column except the first one
```

**Comment by mschuene** [comment]
The clojure.core.matrix/select and clojure.core.matrix/sel methods do what
you are looking for
Am 04.12.2014 07:30 schrieb "Ritchie Cai" notifications@github.com:

**Comment by mikera** [comment]
Willing to consider [start end] instead of [start length]. But would need pretty strong arguments to make this kind of breaking change. Fortunately we can since we're not at 1.0 yet.

Feel free to create an new issue if you feel this is worth debating and you have some strong arguments.
