### ISSUE TITLE
clojure.core.matrix.impl.ndarray-magic/handle-symbol can throw exception

### ISSUE THREAD

**Issue by jafingerhut** [mikera/core.matrix#218]
It does not do so when running core.matrix's own tests -- I only ran across this possibility when testing Eastwood on core.matrix.  Eastwood uses tools.reader when reading source code, which adds :line :column etc. source location metadata to all symbols, which exposes the possibility of an exception.

The exception is in the with-meta call here: https://github.com/mikera/core.matrix/blob/develop/src/main/clojure/clojure/core/matrix/impl/ndarray_magic.clj#L42

The case where this occurs is that sym is a symbol with metadata, but (replaces sym) is a keyword, resulting in an attempted call to with-meta on a keyword, which throws an exception.

I don't have a suggested fix yet, as I have only begun characterizing the problem.  It isn't clear to me whether it is intended to replace a symbol with a keyword in this function.

If so, one way to avoid the exception, but lose the metadata on the symbol, would be to change the condition in the if-let from (meta sym) to (and (instance? clojure.lang.IObj new-sym) (meta sym))

**Comment by mikera** [comment]
Closing because I think this was fixed in the linked PR
