### ISSUE TITLE
efficient column percentages?

### ISSUE THREAD

**Issue by aaelony** [mikera/core.matrix#221]
I'm sure I've written a **terrible implementation** of a function to get column percentages out of a matrix... Hoping someone can enlighten me on a (much) better way?

``` clojure
(ns blah
  (:require [clojure.core.matrix :as m]))

(defn column-percentages
  "Takes a Vector of Vectors containing integers, converts to a Matrix, computes column percentages."
  [vv]
  (let [m (m/matrix vv)
        ncolumns  (first (m/shape m))
        col-sums (m/matrix (into [] (for [i (range 0 ncolumns)]
                                      (reduce + (m/slice (m/transpose m) i)))))
        ]
    (m/div m
         col-sums)))
```

``` clojure
(-> [[1 2 3] [4 5 6] [7 8 9]] column-percentages)
```

``` clojure
#<Matrix [[0.08333333333333333,0.13333333333333333,0.16666666666666666],
[0.3333333333333333,0.3333333333333333,0.3333333333333333],
[0.5833333333333334,0.5333333333333333,0.5]]>
```

**Comment by aaelony** [comment]
Aside from my above attempt being cludgy, even has a bug. Hopefully corrected below...

``` clojure
(defn column-percentages
  "Takes a Vector of Vectors containing integers, converts to a Matrix, computes column percentages."
  [vv]
  (let [m (m/matrix vv)
        ncolumns  (second (m/shape m))
        col-sums (m/matrix (into [] (for [i (range 0 ncolumns)]
                                      (reduce + (m/slice (m/transpose m) i)))))
        ]
    (m/div m
         col-sums)))
```

``` clojure
(-> [[1 2 3] [4 5 6] [7 8 9] [10 11 12] [13 14 15] [16 17 18]] column-percentages m/pm)
```

``` clojure
[[0.020 0.035 0.048]
 [0.078 0.088 0.095]
 [0.137 0.140 0.143]
 [0.196 0.193 0.190]
 [0.255 0.246 0.238]
 [0.314 0.298 0.286]]
```

**Comment by mikera** [comment]
You can make a couple of quick simplifications:

``` clojure
(defn column-percentages
     "Takes a Vector of Vectors containing integers, converts to a Matrix, computes column percentages."
     [vv]
     (let [m (m/matrix vv)
           cols  (m/columns m)
           col-sums (mapv m/esum cols)]
       (m/div m col-sums)))
```

**Comment by aaelony** [comment]
I was actually hoping to use esum, but didn't manage it. thank-you, that's awesome.

**Comment by mikera** [comment]
Technically, you don't even need the `m/matrix` call either, since you can treat a vectors of vectors directly as a matrix:

``` clojure
(defn column-percentages
     "Takes a Vector of Vectors containing integers, converts to a Matrix, computes column percentages."
     [m]
     (let [cols  (m/columns m)
           col-sums (mapv m/esum cols)]
       (m/div m col-sums)))
```

The only big advantage I can see of using `m/matrix` is that it will convert your vector of vectors to the current matrix implementation, so if you are using something like `vectorz-clj` the computation can be much faster. If you want to do that, then using `m/coerce` is even better because it won't make a copy if the data is already in the required format.

**Comment by aaelony** [comment]
Wow, that's cool.  I need to learn the API.  I can see this as something that might be useful in incanter as well to produce percentages.  Or even pull from a database query, transform to vector of vectors (or incanter dataset or whatever it might need to become) and produce percentages..

**Comment by mikera** [comment]
Yep that's the whole idea with `core.matrix`! Lots of handy functions to make data processing pipelines both simple and efficient.

Closing the issue as I think the specific question is resolved, but feel free to open new issues on anything related.
