### ISSUE TITLE
Could not find artifact net.mikera:mikera-pom:pom:0.4.0 in clojars.org (https://clojars.org/repo)

### ISSUE THREAD

**Issue by arohner** [mikera/core.matrix#222]
The root cause of this is likely a lein/maven/aether bug, but it might be something you have control over. 

I tried to add `[net.mikera/core.matrix "0.32.1"]` to my project, but lein deps failed with:

`Caused by: org.sonatype.aether.transfer.ArtifactNotFoundException: Could not find artifact net.mikera:mikera-pom:pom:0.4.0 in clojars.org (https://clojars.org/repo)`

I look on clojars, and see `[net.mikera/mikera-pom "0.0.4"]` exists, but no later version. 

In my project.clj, I replace :repositories with:

``` clojure
^:replace [["central" {:url "https://repo1.maven.org/maven2/" :snapshots false}]
                           ["clojars" {:url "https://clojars.org/repo/"}]]
```

(i.e. explicitly listing central first), and the dep is correctly pulled down from central. 

My suspicion is that having an incomplete list of poms on clojars confused lein, resulting in the error.

**Comment by mars0i** [comment]
Whether or not getting core.matrix from clojars.org works, a general solution that works even with development versions is to install the source locally, then

```
lein deps
lein repl  # make sure everything compiles and works properly
lein install
```

That last step will put the jar file into your local maven directory tree; then you won't need to get it from clojars.

Note  `lein install` overwrites `pom.xml`, so if you are going to make changes to the source and commit them, then your next step after the preceding should be:

```
git stash
```

or something else that will restore pom.xml to the source version.  Also note that sometimes project.clj is behind pom.xml, so you might have to update project.clj before doing `lein deps`, etc.  (In that case, you might want to commit the new project.clj and make a pull request, but if not, someone else will do that eventually.  I have periodically updated project.clj, for example.)

**Comment by mikera** [comment]
`mikera-pom` is on Maven Central rather than clojars:
- https://maven-repository.com/artifact/net.mikera/mikera-pom/0.4.0

Seems like a lein issue rather than anything else? It should be checking Central (or at least, it does for me...)

**Comment by arohner** [comment]
Yes, it is a lein/maven bug, but I think it's caused by the fact that clojars has an _incomplete_ list of versions of mikera-pom. My suspicion of what happened is:

I have

```
:repositories {"my.datomic.com" {:url "https://my.datomic.com/repo"
                                   :username [:gpg :env/datomic_repo_username]
                                   :password [:gpg :env/datomic_repo_password]}}
```

in my project.clj, which caused the repos to re-order. Lein checked clojars first, found that mikera-pom exists, and then didn't find 0.4.0, and maven threw rather than checking central. 

I'll report this to lein, but as a workaround, you could remove the outdated mikera-pom versions from clojars.

**Comment by mikera** [comment]
I'm cautious about nuking old versions in clojars in case people still have a dependency on those (that probably includes myself!). Will give it some though though.

**Comment by mikera** [comment]
Closing this because it's a `lein` issue, nothing to do with `core.matrix`.

@arohner hopefully you found a good workaround in the meantime?

**Comment by arohner** [comment]
I hit this again, in a different project. This time with `Could not find artifact net.mikera:mikera-pom:pom:0.6.0 in clojars.org`, because I was using imagez. 

I still think this is a bug with how you've deployed mikera pom. I think either every version of mikera pom needs to be in clojars, or none of them.

**Comment by arohner** [comment]
Sorry. Looks like this is caused by `lein-npm` doing it's own special form of dependency resolution. Removing it made the error go away.
