### ISSUE TITLE
Setting implementation does not result in registration of imp

### ISSUE THREAD

**Issue by drone29a** [mikera/core.matrix#223]
I've noticed this with Vectorz but imagine it would affect other implementations.

Using `(set-current-implementation :vectorz)` to set Vectorz as the default impl results in `c.c.m.implementations/*matrix-implementation*` being set to :vectorz, but taking a look at `canonical-objects` reveals no entry for Vectorz and when using the core.matrix API to interact with a Vectorz object (e.g., a `SparseRowMatrix`) the default protocol implementations are used.

I can work around this by manually loading `mikera.vectroz.matrix-api` before using the core.matrix API. The vectorz-clj protocol implementations will then be used. I've poked around some at recent changes and so far haven't found a cause.

**Comment by mikera** [comment]
Hmmm it is supposed to trigger a load of the right namespace (in this case `mikera.vectorz.matrix-api`). That in turn should trigger registration of the appropriate canonical object.

**Comment by mikera** [comment]
I think this fixes it: https://github.com/mikera/core.matrix/commit/ab46686bcc1869536d686f05c189579eea3ba00c

**Comment by mikera** [comment]
@mattrepl can you confirm if this is fixed for you in latest release `0.33.2`?

**Comment by drone29a** [comment]
Yep, fixed. Thanks!

**Comment by mikera** [comment]
Awesome thanks for the report and checking!
