### ISSUE TITLE
Core Matrix Dot Product Performance

### ISSUE THREAD

**Issue by satriaenur** [mikera/core.matrix#228]
hello there, i want to ask about core.matrix dot product performance, is there a technique to optimize dot-product function ? ( i don't know whether this question is an issue or anything )

Because i found that in Java, C, or even in HipHipArray library, the dot product performance is extremely faster than core matrix dot product. I conduct a little benchmark by looping the dot product function until 800000 steps, and i found in Java = 12 ms, C = 22 ms, and core.matrix = 1300 ms ( if using core.matrix.dot ), if using hiphip array in clojure, i found its resulting 300 ms for 800000 iteration dot-product. ( I know the benchmark is not apple to apple benchmark, but in hip - hip array i thought it was )

Actually i want to use hiphip array and core matrix when executing the core.matrix.dot-product, but the function dot-product demanding double-array format for the input, which is also bottleneck process for core.matrix because the row of matrix should be cast into double-array form before running dot-product. 

any solution ?

**Comment by mikera** [comment]
What types of array were you using? And what size?

Dot products with regular Clojure vectors are relatively slow (because they use boxed numbers and have some overhead for each lookup), but if you use vectorz vectors (for example) the performance will be much better:

``` clojure
(let [v (array :vectorz [1 2 3])]
     (time (dotimes [i 800000] (dot v v))))
=> "Elapsed time: 30.274709 msecs"
```

If you use type hints and call the Vectorz methods directly, you can also avoid the protocol dispatch overhead, at which point you should be competitive with C or Java:

``` clojure
(let [v (mikera.vectorz.Vector3. (array :vectorz [1 2 3]))]
     (time (dotimes [i 800000] (.dotProduct v v)))
=> "Elapsed time: 14.590674 msecs"
```

**Comment by mikera** [comment]
P.S. I just pushed a commit that optimises dot products for Clojure vectors. Still never going to be as fast as Vectorz, but at least I got a decent improvement:

``` clojure
(let [v [1 2 3]]
     (time (dotimes [i 800000] (dot v v))))
=> "Elapsed time: 196.972893 msecs"
```

**Comment by mikera** [comment]
Final note, you can also use double arrays directly with core.matrix. This can be handy sometimes, and it is also pretty fast for many operations:

``` clojure
(let [v (double-array [1 2 3])]
     (time (dotimes [i 800000] (dot v v))))
=> "Elapsed time: 36.123667 msecs"
```

**Comment by satriaenur** [comment]
ok, here is the source code

``` clojure
(time (dotimes [i 800000] (dot [5 5 5 5 5 5 5 5 5 5] [5 5 5 5 5 5 5 5 5 5]))) 
=> "Elapsed time: 1172.994 msecs"
```

the vector length is 10, and it could be larger than 10. 

i was worrying, when i'm doing this

``` clojure
# def P matrix 943 x 10, def qt 1682 x 10
(time (dotimes [i 800000] (dot (get-row P 1) (get-column qt 1))) 
```

the time process should be larger than executing [5 5 5 5 5 5 5 5 5 5] array.

**Comment by satriaenur** [comment]
The question is actually i want to perform matrix dot product with another different row matrix for each iteration, if we are performing with 

``` clojure
(let [v (get-row P 1)] ... )
```

definitely, it will memoize the last row

**Comment by mikera** [comment]
@satriaenur using the `:vectorz` implementation should definitely be faster for your use case. Especially true if you are planning to slice by rows / columns. See e.g.

``` clojure
(let [v (array :vectorz [5 5 5 5 5 5 5 5 5 5])]
     (time (dotimes [i 800000] (dot v v))) )
"Elapsed time: 22.990836 msecs"
```

Clojure vectors are great in many ways, but they aren't really optimised for numerical code.

**Comment by satriaenur** [comment]
@mikera phew, i think my problem is not set the implementation of those matrix. Thanks for the explanation, somehow it works like a charm! :+1:

**Comment by mikera** [comment]
No worries - glad it works for you!
