### ISSUE TITLE
Π and Σ names cause a run error

### ISSUE THREAD

**Issue by puradawid** [mikera/core.matrix#230]
Stacktrace:

> Exception in thread "main" java.lang.NoClassDefFoundError: clojure/core/matrix/operators$Σ (wrong name: clojure/core/matrix/operators$Π), compiling:(/tmp/form-init1542665343607847567.clj:1:72)
>         at clojure.lang.Compiler.load(Compiler.java:7142)
>         at clojure.lang.Compiler.loadFile(Compiler.java:7086)
>         at clojure.main$load_script.invoke(main.clj:274)
>         at clojure.main$init_opt.invoke(main.clj:279)
>         at clojure.main$initialize.invoke(main.clj:307)
>         at clojure.main$null_opt.invoke(main.clj:342)
>         at clojure.main$main.doInvoke(main.clj:420)
>         at clojure.lang.RestFn.invoke(RestFn.java:421)
>         at clojure.lang.Var.invoke(Var.java:383)
>         at clojure.lang.AFn.applyToHelper(AFn.java:156)
>         at clojure.lang.Var.applyTo(Var.java:700)
>         at clojure.main.main(main.java:37)
> Caused by: java.lang.NoClassDefFoundError: clojure/core/matrix/operators$Σ (wrong name: clojure/core/matrix/operators$Π)
>         at java.lang.ClassLoader.defineClass1(Native Method)
>         at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
>         at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
>         at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
>         at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
>         at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
>         at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
>         at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>         at clojure.core.matrix.operators__init.load(Unknown Source)
>         at clojure.core.matrix.operators__init.<clinit>(Unknown Source)
>         at java.lang.Class.forName0(Native Method)
>         at java.lang.Class.forName(Class.java:344)
>         at clojure.lang.RT.loadClassForName(RT.java:2093)
>         at clojure.lang.RT.load(RT.java:430)
>         at clojure.lang.RT.load(RT.java:411)
>         at clojure.core$load$fn__5066.invoke(core.clj:5641)
>         at clojure.core$load.doInvoke(core.clj:5640)
>         at clojure.lang.RestFn.invoke(RestFn.java:408)
>         at clojure.core$load_one.invoke(core.clj:5446)
>         at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
>         at clojure.core$load_lib.doInvoke(core.clj:5485)
>         at clojure.lang.RestFn.applyTo(RestFn.java:142)
>         at clojure.core$apply.invoke(core.clj:626)
>         at clojure.core$load_libs.doInvoke(core.clj:5524)
>         at clojure.lang.RestFn.applyTo(RestFn.java:137)
>         at clojure.core$apply.invoke(core.clj:626)
>         at clojure.core$require.doInvoke(core.clj:5607)
>         at clojure.lang.RestFn.invoke(RestFn.java:421)
>         at clojure.core.matrix.examples$loading__4958__auto__.invoke(examples.clj:1)
>         at clojure.core.matrix.examples__init.load(Unknown Source)
>         at clojure.core.matrix.examples__init.<clinit>(Unknown Source)
>         at java.lang.Class.forName0(Native Method)
>         at java.lang.Class.forName(Class.java:344)
>         at clojure.lang.RT.loadClassForName(RT.java:2093)
>         at clojure.lang.RT.load(RT.java:430)
>         at clojure.lang.RT.load(RT.java:411)
>         at clojure.core$load$fn__5066.invoke(core.clj:5641)
>         at clojure.core$load.doInvoke(core.clj:5640)
>         at clojure.lang.RestFn.invoke(RestFn.java:408)
>         at clojure.core$load_one.invoke(core.clj:5446)
>         at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
>         at clojure.core$load_lib.doInvoke(core.clj:5485)
>         at clojure.lang.RestFn.applyTo(RestFn.java:142)
>         at clojure.core$apply.invoke(core.clj:626)
>         at clojure.core$load_libs.doInvoke(core.clj:5524)
>         at clojure.lang.RestFn.applyTo(RestFn.java:137)
>         at clojure.core$apply.invoke(core.clj:626)
>         at clojure.core$require.doInvoke(core.clj:5607)
>         at clojure.lang.RestFn.invoke(RestFn.java:457)
>         at com.tangramcare.spark.util.mllib$loading__4958__auto__.invoke(mllib.clj:1)
>         at com.tangramcare.spark.util.mllib__init.load(Unknown Source)
>         at com.tangramcare.spark.util.mllib__init.<clinit>(Unknown Source)
>         at java.lang.Class.forName0(Native Method)
>         at java.lang.Class.forName(Class.java:344)
>         at clojure.lang.RT.loadClassForName(RT.java:2093)
>         at clojure.lang.RT.load(RT.java:430)
>         at clojure.lang.RT.load(RT.java:411)
>         at clojure.core$load$fn__5066.invoke(core.clj:5641)
>         at clojure.core$load.doInvoke(core.clj:5640)
>         at clojure.lang.RestFn.invoke(RestFn.java:408)
>         at clojure.core$load_one.invoke(core.clj:5446)
>         at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
>         at clojure.core$load_lib.doInvoke(core.clj:5485)
>         at clojure.lang.RestFn.applyTo(RestFn.java:142)
>         at clojure.core$apply.invoke(core.clj:626)
>         at clojure.core$load_libs.doInvoke(core.clj:5524)
>         at clojure.lang.RestFn.applyTo(RestFn.java:137)
>         at clojure.core$apply.invoke(core.clj:626)
>         at clojure.core$require.doInvoke(core.clj:5607)
>         at clojure.lang.RestFn.invoke(RestFn.java:619)
>         at com.tangramcare.spark.d2.classifiers.whitening$loading__4958__auto__.invoke(whitening.clj:1)
>         at com.tangramcare.spark.d2.classifiers.whitening__init.load(Unknown Source)
>         at com.tangramcare.spark.d2.classifiers.whitening__init.<clinit>(Unknown Source)
>         at java.lang.Class.forName0(Native Method)
>         at java.lang.Class.forName(Class.java:344)
>         at clojure.lang.RT.loadClassForName(RT.java:2093)
>         at clojure.lang.RT.load(RT.java:430)
>         at clojure.lang.RT.load(RT.java:411)
>         at clojure.core$load$fn__5066.invoke(core.clj:5641)
>         at clojure.core$load.doInvoke(core.clj:5640)
>         at clojure.lang.RestFn.invoke(RestFn.java:408)
>         at clojure.core$load_one.invoke(core.clj:5446)
>         at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
>         at clojure.core$load_lib.doInvoke(core.clj:5485)
>         at clojure.lang.RestFn.applyTo(RestFn.java:142)
>         at clojure.core$apply.invoke(core.clj:626)
>         at clojure.core$load_libs.doInvoke(core.clj:5524)
>         at clojure.lang.RestFn.applyTo(RestFn.java:137)
>         at clojure.core$apply.invoke(core.clj:626)
>         at clojure.core$require.doInvoke(core.clj:5607)
>         at clojure.lang.RestFn.invoke(RestFn.java:408)
>         at user$eval7$fn__9.invoke(form-init1542665343607847567.clj:1)
>         at user$eval7.invoke(form-init1542665343607847567.clj:1)
>         at clojure.lang.Compiler.eval(Compiler.java:6703)
>         at clojure.lang.Compiler.eval(Compiler.java:6693)
>         at clojure.lang.Compiler.load(Compiler.java:7130)
>         ... 11 more

It happens on linux only when i run from lein my class which requires clojure.core.matrix Is it a good name for a function that compiles to a Java class? It is my shot but ext3 for example seems to not support full Unicode.

**Comment by mikera** [comment]
Guess these might be bad names to use.... will have to figure out if this is actually a Clojure bug, it might be that the names are not getting mapped correctly to valid class names.

**Comment by mikera** [comment]
Have removed these for now.
