### ISSUE TITLE
select on persistent-vector returns ndarray

### ISSUE THREAD

**Issue by mars0i** [mikera/core.matrix#237]
``` clojure
(select (matrix :persistent-vector [10 20 30 40]) [0 2])
; => #object[clojure.core.matrix.impl.wrappers.NDWrapper 0x64b99636 "[10 30]"]
```

From comments in other issues, I'm guessing that this might be more efficient than returning a persistent-vector, which would obviously require creating a new matrix.  Maybe given an ndarray input, `select` doesn't create a new matrix?  I'm not sure that returning an ndarray from a persistent-vector is desirable, though.  A new ndarray matrix has to be created, and this behavior prevents use of `select` by someone who's working exclusively with Clojure vectors.

Note: `select` on a vectorz matrix does return a vectorz matrix.

I think the persistent-vector -> ndarray behavior results from the following:

In clojure.core.matrix.impl.default:

``` clojure
(extend-protocol mp/PSelect
  Object
  (select [a area]
    (wrap/wrap-selection a area)))
```

In clojure.core.matrix.impl.wrappers:

``` clojure
(defn wrap-selection
  [m indices]
  (let [shp (long-array (map count indices))
        dims (count shp)]
    (NDWrapper.
     m
     shp
     (long-array (range dims))
     (object-array (map long-array indices))
     (long-array (repeat dims 0))
     )))
```

It may be that the intention was to deal with persistent-vector later.  However, I didn't find an issue that documented the problem.  (But I might be missing something, and I don't fully understand the code here at the moment, in any event.)

**Comment by mikera** [comment]
We should probably override `mp/PSelect` for persistent vectors. Currently the default "Object" implementation is being used, which works but may be slower.

I think doing a custom implementation for "IPersistentVector" and returning a new persistent vector would be a net win (especially if we do it via populating an object array directly, rather than repeated `conj`-ing)

**Comment by fyquah** [comment]
Looks like `select` on java double arrays are returning NDArray objects. I am assuming we are expecting a double array instead of a NDArray object?

**Comment by mikera** [comment]
Yes I think double arrays should normally be returned by select on double arrays. 

Likewise for most implementations, although there are cases where performance may be better using a different implementation. We'll need to evaluate these case by case, but the general rule should usually be that each implementation returns it's own type.

**Comment by mikera** [comment]
Closing because this is now fixed in latest release
