### ISSUE TITLE
Matrix construction from 1D array

### ISSUE THREAD

**Issue by malloc82** [mikera/core.matrix#238]
Is there a efficient way to construct a matrix from a 1-D array of raw data? Currently I can do it with the two ways:

```
1. (reshape (matrix *raw_data*))
2. (matrix (convert-to-2D *raw_data*))
```

Both require additional memory copy of that raw data. It's not quite desirable when I'm dealing with a lot of matrices. For example, when I'm reading data off an image, they usually come out as an 1D array. Vectorz does have an constructor to do this but it's a private method.

Is it possible to add a constructor supporting 1-D raw data with specified dimension information?

**Comment by mikera** [comment]
Efficiency is pretty implementation dependent, i.e. it depends on what both your source data and target implementation happens to be. What implementation are you using, and what type is `*raw_data*`?

e.g. There are much faster ways to do it in `vectorz-clj`: if your input data is a double array you can actually wrap it as a vector, matrix or nd-array in an O(1) operation.

**Comment by malloc82** [comment]
My input raw data usually are double array. So both wrap and reshape in vectorz-clj are O(1)?

**Comment by mikera** [comment]
O(1) wrap exists for double arrays but I think you need to call the Java directly e.g. `(mikera.matrixxx.Matrix/wrap darray rows cols)`. Haven't yet created a `core.matrix` API function that exposes this directly.

Functions like `reshape`, `transpose` etc. are generally O(1) for most `Vectorz` objects. Usually these operations just change the indexing into the same backing array.

**Comment by malloc82** [comment]
```
(mikera.matrixx.Matrix/wrap rows cols darray)
```

Ok, that works. However, reshape do make a copy of the internal double array, right? Won't that make it O(n)? I tried: 

```
(def darray (double-array (range 1280000)))
(time (reshape (time (matrix :vectorz darray)) [1280 1000]))
```

It seems the reshape takes about twice the time, that should be due to allocating memory for the new matrix.
Is it possible to add a mutable reshape! like the one in clatrix?

**Comment by mikera** [comment]
A mutable reshape is a possible idea.... though I'm trying to avoid mutability as much as possible in `core.matrix`.

Vectorz will happily let you re-wrap the same underlying array however, which may be all that you need if you want to avoid copying the array:

``` clojure
(def v (array :vectorz [1 2 3 4 5 6]))
(def m (mikera.matrixx.Matrix/wrap 3 2 (.asDoubleArray v)))
(identical? (.asDoubleArray v) (.asDoubleArray m))
=> true
```

Note the subtle difference between `.asDoubleArray` (which returns the underlying array, if it exists) and `.toDoubleArray` (which copies the elements into a new double array)

**Comment by mikera** [comment]
Closing as I don't think there are any outstanding points to be addressed.
