### ISSUE TITLE
Implement support for 2D double arrays

### ISSUE THREAD

**Issue by mikera** [mikera/core.matrix#247]
Currently core.matrix has optimised implementations for 1D `double[]` arrays (considered as vectors)

It would be valuable to extend this to 2D `double[][]` arrays, since these are frequently used to represent matrices.

This could be achieved by adding extra protocol implementations for 2D double arrays to the following file:
https://github.com/mikera/core.matrix/blob/develop/src/main/clojure/clojure/core/matrix/impl/double_array.clj

**Comment by fyquah** [comment]
I wish to try implementing this.

Should I extend the current implementation for 1D, or create a new implementation for 2D double arrays?

Extending the current implementations might have a problem - `double[]` and `double[][]` doesn't seem to have any common superclasses but `Cloneable`, `Object` and `Serializable` . Trying the create a new implementation should make the thing run faster, at the expense of a more repetitive code.

**Comment by mikera** [comment]
I think you will need to implement separate code, at least for the protocol implementations. You may be able to factor out some stuff into common code however.

Suggest starting with one or two protocols first to check out the concept and work out the quirks, type hinting etc.?

**Comment by fyquah** [comment]
I have implemented a small part of it:

https://github.com/fyquah95/core.matrix/commit/44aab01e904f84f4667ea1079a7cc2f55c0fa178#diff-ae5d6a229db679de830dcd7704ff3bd3R40

The `construct-double-array` function for 2d arrays seems to be too slow. The bottleneck is probably the loop :

``` clojure
user=> (def d (make-array Double/TYPE 1000 1000))
user=> (time (dotimes [i 1000]
  #_=>          (dotimes [j 1000]
  #_=>              (aset-double d i j 1.0))))
"Elapsed time: 9341.115515 msecs"
```

Anyway to improve this?

**Comment by mikera** [comment]
I suspect that Clojure isn't optimising the 2D array access. You are probably better off with something like (untested):

``` clojure
(dotimes [i 1000]
  (let [^doubles row (aget d i)] 
    (dotimes [j 1000]
      (aset row j 1.0))))
```

**Comment by mikera** [comment]
Closing this issue as the support has now been merged. Thanks @fyquah95 !
