### ISSUE TITLE
Convert list-of-lists to dataset is far slower then list->matrix->dataset

### ISSUE THREAD

**Issue by behrica** [mikera/core.matrix#253]
The following code runs 200 times slower in the first case.

```
(require '[ clojure.core.matrix.dataset :as ds])
 (require '[ clojure.core.matrix :as m])

 (def data  (repeat 1000 (repeat 1000 "1")))

(def ds1 (time  (ds/dataset data)))
(def ds2 (time  (ds/dataset (m/matrix data))))


```

"Elapsed time: 27536.0122 msecs"
"Elapsed time: 214.367115 msecs"

I mentioned this already as an incanter issue:
https://github.com/incanter/incanter/issues/282

but it is better placed here.

**Comment by mikera** [comment]
I think the root problem is that the implementation for `:sequence` reading isn't yet very optimised. We don't really want sequences to be used as array implementations, but it _may_ make sense to have sequences as input (e.g. as lazy sequences for reading big datasets etc.)

Will have a quick think about the best way to solve this.

**Comment by behrica** [comment]
This issue is mainly solved.
I could still see that the second version is still faster (factor 2),
but this is obviously a large improvement compared to the factor 100 speed difference of before.  

I will now check with incanter, to how the imprtoved code works there.

**Comment by mikera** [comment]
OK cool I will make a new release today
