### ISSUE TITLE
nd4j backend

### ISSUE THREAD

**Issue by huahaiy** [mikera/core.matrix#254]
Any plan to include [nd4j](https://github.com/deeplearning4j/nd4j) as a backend? It supports GPU.

See also @whilo https://github.com/whilo/clj-nd4j

**Comment by mikera** [comment]
Yes the clj-nd4j repo you link to should provide nd4j support in core.matrix

Feel free to hack on it and contribute!

I've also been experimenting with GPU support in vectorz-clj in the following repo via netlib-java:
https://github.com/mikera/vectorz-clj
