### ISSUE TITLE
set-selection! not doing what it's described

### ISSUE THREAD

**Issue by malloc82** [mikera/core.matrix#257]
According to doc string set-selection! is a destructive version of set-selection. The following code shows set-selection behaves:

``` clojure

(ns test.core
  (:require [clojure.core.matrix :as mat])
  (:import [mikera.matrixx Matrix]))

(mat/set-current-implementation :vectorz)

(def m (mat/new-matrix 3 4))
;; #vectorz/matrix [[0.0,0.0,0.0,0.0],
;; [0.0,0.0,0.0,0.0],
;; [0.0,0.0,0.0,0.0]]

(mat/set-selection m :all 0 (Matrix/wrap 3 1 (into-array Double/TYPE [3.0 4.0 5.0])))
;; #Vectorz/matrix [[3.0,0.0,0.0,0.0],
;; [4.0,0.0,0.0,0.0],
;; [5.0,0.0,0.0,0.0]]
```

The returned result is a new matrix with first column updated with [3.0 4.0 5.0]. 

However, if I use set-selection! instead set-selection, the returned matrix is the original, unmodified m and m remain untouched.

``` clojure
(mat/set-selection! m :all 0 (Matrix/wrap 3 1 (into-array Double/TYPE [3.0 4.0 5.0])))
;; #vectorz/matrix [[0.0,0.0,0.0,0.0],
;; [0.0,0.0,0.0,0.0],
;; [0.0,0.0,0.0,0.0]]
```

Am I doing it wrong?

**Comment by malloc82** [comment]
I guess the alternative will be using assign! with submatrix? This seems to work:

``` clojure
(mat/assign! (mat/submatrix m [[0 3] [2 1]])
             (Matrix/wrap 3 1 (into-array Double/TYPE [3.0 4.0 5.0])))
```

**Comment by mikera** [comment]
That looks like it could be a vectorz-clj bug. I will take a look, thanks! 

Your workaround should work well though (in fact it is probably my recommended approach).

Also note that you can use `(reshape [3 4 5] [3 1])` or `(column-matrix [3 4 5])` to get your column matrix, this is better than using the Java interop since it avoids depending on Vectorz implementation details.

**Comment by malloc82** [comment]
Just curious is the view returned by select meant to be mutable? From some tests, it seems not, but set-selection! does treat it like one.

**Comment by mikera** [comment]
select should return a mutable view if the implementation supports them. I am not sure if this is happening everywhere it should however... this probably needs better testing.

**Comment by mikera** [comment]
I'm considering having a separate select-view for when people want view semantics

**Comment by malloc82** [comment]
It's going to be immutable and for view only?

**Comment by malloc82** [comment]
Also are select syntax meant to replace submatrix in the future?

**Comment by mikera** [comment]
The view version is generally intended for mutable views. If you don't care whether you get a view or not, then the simple version is probably better.

slect is not really intended to replace submatrix.... select is more general (you can do more) but submatrix is likely to have better performance (in Vectorz it is O(1) for example....)

**Comment by mikera** [comment]
This should all be fixed now in the new develop branch. Thanks for the report!

**Comment by malloc82** [comment]
Awesome! Thanks!
