### ISSUE TITLE
error on comparison operations

### ISSUE THREAD

**Issue by carocad** [mikera/core.matrix#261]
Hello,
I just started using core.matrix so I am not fully sure if I am doing something wrong but I am quite confident that this is a bug.

If you check the implementation of the "min" and "max" functions, they are exactly the same!
In fact, the implementation of max doesnt even check that the numbers are th maximum but rather the minimum. See https://github.com/mikera/core.matrix/blob/2f24c2d4114f26d0b90979ac3e64576d0cdfdbe3/src/main/clojure/clojure/core/matrix/operators.clj

As another side note, I was expecting that using (min (array :vectorz [1 2 3])) would return 1, but instead it returns the array itself. I had to use (apply min (array :vectorz [1 2 3])). Is this behavior intended?

**Comment by mikera** [comment]
Fixed in latest develop branch - thanks for the report!

**Comment by mikera** [comment]
Please not that if you want to find the smallest element in an array you should use `emin` (element minimum) instead of `min` (minimum of corresponding elements in different arrays)

Compare:

``` clojure
(emin [1 2 3])
=>1.0

(min [1 2 3] [2 2 2])
=> [1 2 2]
```

**Comment by carocad** [comment]
hey guys,
thanks for fixing this so quickly :D
Oh I see now, I didn't know this other function, but then may I suggest that the min function should have an arity of two or more? if there is already an emin function which is supposed to work on a single array, then why does the min function also works on a single array? it seems counterintuitive to me.
Also as you can see in the code itself, the min function just return the array given for arity 1, so why call the function anyway?

As a side note: Although this might be better on a different issue, is it possible to have a function which returns the minimum and the index of the minimum of the array a sort of "emin-index"? I would be happy to help with this if necessary as I would benefit from it as well.

**Comment by mikera** [comment]
@carocad `min` and `emin` do very different things. 

`min` gets the minimum value of corresponding elements in multiple arrays, i.e. the result is an array. It makes sense to support multiple arity.

`emin` finds the minimum value in a single array. The result is a scalar. It wouldn't make much sense to support multiple arrays (or at least, if that's what the user wants then it is better for them to code it explicitly with something like `(apply min (map emin arrays))`
