### ISSUE TITLE
can't import matrix.random namespace - missing dependency

### ISSUE THREAD

**Issue by timgluz** [mikera/core.matrix#265]
Hi,

i'm using the latest release (0.47.1)  and when i tried to import [clojure.core.matrix.random](https://github.com/mikera/core.matrix/blob/develop/src/main/clojure/clojure/core/matrix/random.clj) namespace in my REPL  i saw this error message:

```
CompilerException java.io.FileNotFoundException: Could not locate mikera/cljutils/error__init.class or mikera/cljutils/error.clj on classpath., compiling:(clojure/core/matrix/random
.clj:1:1)
```

Do i have to include mikera.cljutils into my project dependencies or it should come with core.matrix?

**Comment by mikera** [comment]
Ah.... that should no longer be a required dependency but looks like this one slipped through the net. The next core.matrix release (today!) will address this

**Comment by timgluz** [comment]
Ok, thanks!

**Comment by mikera** [comment]
I have a core.matrix release ready, should be able to upload it as soon as the problem with clojars is fixed
