### ISSUE TITLE
mp/dimensionality doesn't work with instances created by `vector-of`

### ISSUE THREAD

**Issue by smee** [mikera/core.matrix#266]
Clojure provides specialized implementations for vectors of primitive types. They can be constructed via 

``` clojure
(clojure.core/vector-of :double [1 2 3])
```

This vector has no `.length` method, which gets called by https://github.com/mikera/core.matrix/blob/develop/src/main/clojure/clojure/core/matrix/impl/persistent_vector.clj#L536

I'm not sure, whether the implementation in https://github.com/clojure/clojure/blob/bc186508ab98514780efbbddb002bf6fd2938aee/src/clj/clojure/gvec.clj#L240 is wrong because it does not provide a `length` method that is part of the interface IPersistentVec, or if core.matrix should not rely on the method being present?

Example: I see these stacktraces:

```
Unhandled java.lang.AbstractMethodError
   Method clojure/core/Vec.length()I is abstract

                  gvec.clj:   -1  clojure.core.Vec/length
     persistent_vector.clj:  448  clojure.core.matrix.impl.persistent-vector/eval58645/fn
             protocols.clj:   57  clojure.core.matrix.protocols/eval51053/fn/G
                matrix.clj:  436  clojure.core.matrix/matrix?
                matrix.clj:  433  clojure.core.matrix/matrix?
```

**Comment by mikera** [comment]
Hmmm that looks like a Clojure bug. Anything that implements `IPersistentVector` should support `.length`.

Surprised that nobody has run into this before.... is this perhaps a new 1.8 issue?

**Comment by smee** [comment]
Okay, then I will file a bug report there, thanks.

**Comment by smee** [comment]
Bug submitted to the clojure JIRA at http://dev.clojure.org/jira/browse/CLJ-1887

**Comment by mikera** [comment]
Cool, thanks! Will leave this open as a reminder for anyone who runs into the same problem until Clojure gets patched
