### ISSUE TITLE
Make min and max available in core

### ISSUE THREAD

**Issue by Somelauw** [mikera/core.matrix#268]
The min and max functions only appear in core.matrix/operator.
I think the min and max functions should be available in core.matrix as well, for the few who don't like to override the built-in min and max functions.
These are also the only functions in the operator namespace not available in the core.
For example, \* has mul as equivalent.

**Comment by mikera** [comment]
I'm trying to avoid having any functions in `clojure.core.matrix` clash names with `clojure.core`... so not sure if this is a good idea.

**Comment by mikera** [comment]
Closing because we want to avoid name conflicts with clojure.core for now.
