### ISSUE TITLE
Transposing nd-array

### ISSUE THREAD

**Issue by AlejandroCatalina** [mikera/core.matrix#274]
Hi,

First of all, thanks for the amazing develop going on here, `core.matrix` is being really helpful while developing a `NetCDF` library access and data handling for Eumetsat SEVIRI channels.

Nonetheless, I've found that the function 

``` clojure
(transpose matrix dim-ordering)
```

 is not yet implemented. I just wanted to ask how the development is going on this one and/or any tips I could use to either implement it and contribute it back or workaround it for the meantime.

Thank you.

**Comment by mikera** [comment]
Hi @AlejandroCatalina it is certainly on the todo list, a PR would be appreciated if you are keen to tackle it!

The strategy should probably be:
- Create a protocol in `c.c.m/protocols.clj`
- Make an implementation that works for `clojure.lang.IPersistentVector` in `c.c.m.impl/persistent-vector.clj`
- Create a "default" implementation for `java.lang.Object` in `c.c.m.impl/default.clj`. In the first instance this can simply corece to persistent vector, do the transpose using the implementation above, then convert back to the original implementation
- Add some tests in the compliance tester. At the very minimum, prove that behaviour is the same as the single arity transpose if the dimensions are reversed.

**Comment by mikera** [comment]
After the above is done, transpose should work for any implementation (if a little slowly). Other implementations can then add optimised versions as needed (certainly vectorz-clj and ndarray should do this, because their data structures allow for fast in-place transposes)

**Comment by AlejandroCatalina** [comment]
Thank you for your answer @mikera . I'll work on it, hope to get news soon ;).

**Comment by AlejandroCatalina** [comment]
Okay so I've been playing a little on this and I've got an implementation that works in `c.c.m/matrix.clj` but when I write that implementation in `c.c.m.impl/default.clj` it doesn't get called and throws me an `ArityException`. 

Also, in `c.c.m.impl/persistent-vector.clj` there isn't any implementation of `transpose` at all, i've seen it calls the one placed in `c.c.m/matrix.clj`. 

Any tips?

**Comment by mikera** [comment]
Have you checked that you are implementing the protocol correctly? Should look something like the implementation for transpose:

https://github.com/mikera/core.matrix/blob/develop/src/main/clojure/clojure/core/matrix/impl/default.clj#L590 

If you are getting an arity exception, you will need to check the number of arguments carefully. There should be exactly one more argument compared to the regular PTranspose protocol (i.e. the dimension ordering vector)

**Comment by AlejandroCatalina** [comment]
Yes, I think I've solved it. I'm adding some tests.

**Comment by mikera** [comment]
Have added this myself for core.matrix 0.55.0 - let me know if it works for you!
