### ISSUE TITLE
Is there any way to unbox a scalar matrix?

### ISSUE THREAD

**Issue by jwvdm** [mikera/core.matrix#275]
The following code

``` clojure
(+ 1.0 (scalar-matrix 1.0))
```

produces an error:

```
ClassCastException mikera.vectorz.Scalar cannot be cast to java.lang.Number  clojure.lang.Numbers.add (Numbers.java:128)
```

Is there any way to take a `vectorz.Scalar` instance and turn it back into a `Number`?

**Comment by mikera** [comment]
Yup, just use `(mget scalar-array)`, i.e. do an indexed get with no indexes

**Comment by mikera** [comment]
Alternatively, you can use `clojure.core.matrix/add` rather than `clojure.core/+`.... this should handle mixing both scalars and 0d arrays
