### ISSUE TITLE
cannot add to diagonal-matrix

### ISSUE THREAD

**Issue by jwvdm** [mikera/core.matrix#277]
Running the following code (using the vectorz implementation)

``` clojure
(add (diagonal-matrix [1 2 3]) 4)
```

produces the error

```
UnsupportedOperationException class mikera.vectorz.impl.ZeroVector is immutable!  mikera.vectorz.impl.ZeroVector.unsafeSet (ZeroVector.java:139)
```

Apologies if this is a duplicate of something, I searched briefly but did not immediately find hits.

**Comment by mikera** [comment]
Fixed in vectorz develop branch - will make a new release soon.

Thanks for the report!
