### ISSUE TITLE
0.50.0 not getting pulled from clojars?

### ISSUE THREAD

**Issue by paultopia** [mikera/core.matrix#278]
This might be me being stupid... but it also might be a glitch over here, not sure.  After beating my head on the issue described in [this SO](http://stackoverflow.com/questions/36051140/clojure-classpath-troubles-loading-code-and-dependencies-with-leiningen) for a while, I just created a dummy project to see if I can get core.matrix to load.  

With this project.clj 

```
(defproject mtest "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.6.0"] [net.mikera/core.matrix "0.50.0"]])

```

I fire up the repl, and, per the [getting started guide](https://github.com/mikera/core.matrix/wiki/Getting-Started-Guide), simply try to use it with `(use 'clojure.core.matrix)`, I'm treated with the following sad error: `FileNotFoundException Could not locate clojure/core/matrix__init.class or clojure/core/matrix.clj on classpath:   clojure.lang.RT.load (RT.java:443)`

I've confirmed by running `lein classpath` that something that looks like core.matrix is in there -- one entry is `/Users/<my username>/.m2/repository/net/mikera/core.matrix/0.50.0/core.matrix-0.50.0.jar` --- so maybe this is some kind of problem with whatever's in clojars?

**Comment by paultopia** [comment]
Aaah.  Tracked it down: it looks like it wants clojure 1.8.0; leiningen was giving me 1.6.0 by default for some reason.  When I list 1.8.0 as a dependency it runs fine.  Maybe this should be noted in the [getting started guide](https://github.com/mikera/core.matrix/wiki/Getting-Started-Guide)?

**Comment by mikera** [comment]
It needs Clojure 1.7 (because it now requires cljc). Will add a comment in the guide! Thanks for reminding me!
