### ISSUE TITLE
README note on *warning on reflection*

### ISSUE THREAD

**Issue by carocad** [mikera/core.matrix#280]
Hey guys,
I am not entirely sure if this should be here or on vectorz-clj as that is the implementation I use. Nevertheless I think that the main problem I wish to discuss should be documented here. 

The problem is caused by the reflections that come from the interaction between core.matrix and clojure. I was using compute-matrix with two other matrices to calculate the distance between each pair of vectors. The matrix was around 200x200 elements. Which is not much. In the beginning I was passing each vector as a Clojure Persistent Vector but internally they were casted to AVector (vectorz), the distance was computed and then they were casted back to Persistent Vector.
I was not aware at all of this behavior and there was no flag nor a comment anywhere about it.

I then read about the _warning on reflection_ flag in clojure and `lein check` and after fixing those I got a 100x speed up !!

I know that it is practically not possible to ensure that the arguments are going to be in the expected type, but I think that it would be worth to mention things like this on the documentation.
Maybe a section on the wiki `Fast computation tips`? or in the README?

This could probably help people understand differences between the different implementations and speeds as stated in #55

**Comment by mikera** [comment]
I'd be happy to take any PRs which fix reflection! Ideally there shouldn't be any reflection warnings in any core.matrix implementation, but it is possible that a few slipped through the net.

The idea is that any differences in types should be handled by protocols, which are pretty fast and avoid reflection.

Also happy if you want to add some fast computation tips to the Wiki! But I think fixing up the reflections is more important than warning people about them :-)

**Comment by carocad** [comment]
hmm maybe I didn't explained that correctly. I didn't find any reflection warning on core.matrix itself. What was slowing down my code was the interaction between Clojure sequences and core.matrix's implementation.

Let me show you what I mean:

``` Clojure
(defn point-distance
  "computes the distance between all the possible point combinations of the two
  curves P and Q using the dist-fn"
  [P Q dist-fn]
  (compute-matrix :vectorz [(row-count P) (row-count Q)]
                  (fn [ i j] (dist-fn (get-row P i) (get-row Q j)))))
```

This is a very simple code, which nevertheless was my bottleneck. P and Q are two matrices and dist-fn is just a function that knows how to compute the distance between any two rows of P and Q. At first I didn't see any problem with this code but there is a very expensive cast going on there.

Imagine that P and Q are not passed as matrices but as Vectors of Vectors (Clojure's PersistentVector). From what I found, vectorz-clj doesn't have any implementation of get-row for Clojure's collections ([see code here](https://github.com/mikera/vectorz-clj/blob/0c2a61b9b077a25e3f090944aa2d265ae49eb51e/src/main/clojure/mikera/vectorz/matrix_api.clj#L805-L813)), which means that any time that get-row is called, a reflection is produced from Clojure's PersistentVector to vectorz-clj's AMatrix.  In my case the computed matrix was around 200x200 elements, which is not that big, but since get-row is called 2 times for each computation that makes it 200*200*2 = 80000 which are a lot of reflections !

As I said, I'm not sure if the problem is on core.matrix itself as ensuring that the input is in the correct format should be the work of the user. That's the reason why I mentioned the Fast computation Wiki entry. In my case I created a simple protocol which wraps the input in a Matrix if they are instances of Clojure's Sequences, if they are already a AMatrix then it is returned without any change.

I would be happy to collaborate with the wiki or/and with a pull request if necessary. But I'm not that experience to know if the problem described has an implementation solution or rather only a wiki solution from the user side. I would like to know your opinion about it.

**Comment by mikera** [comment]
There shouldn't be reflection happening at all in that operation, so yes it looks like an implementation issue. Not sure if it is core.marix or vectorz-clj though. I will take a look when I get some time.

As a temp workaround, you may find that creating a :vectorz matrix and using `mset` to set elements in a nested loop is faster.

**Comment by mikera** [comment]
OK so I think the real problem here is that you are coercing rows for every [i j] combination. A better approach would be to coerce the types once, e.g. something like:

``` clojure
(defn point-distance
  "computes the distance between all the possible point combinations of the two
  curves P and Q using the dist-fn"
  [P Q dist-fn]
  (let [P (coerce :vectorz P)
         Q (coerce :vectorz Q]
    (compute-matrix :vectorz [(row-count P) (row-count Q)]
                  (fn [ i j] (dist-fn (get-row P i) (get-row Q j))))))
```

This way the coercion to AMatrix only happens once, and get-row should use the fast (no-copying) Vectorz implementation

**Comment by carocad** [comment]
@mikera I was fully aware of the problem being the coercing part for every combination. In fact I wrote it in the message before: 

> From what I found, vectorz-clj doesn't have any implementation of get-row for Clojure's collections (see code here), which means that any time that get-row is called, a reflection is produced from Clojure's PersistentVector to vectorz-clj's AMatrix

That's the reason why I suggested putting a note either on the wiki or on the docstring since the docstring doesn't explicitely says that AMatrix type is expected for `get-row|get-column`. I think that something similar to Clojure's note on `next` might suffice.

> next: Returns a seq of the items after the first. Calls seq on its
> argument.  If there are no more items, returns nil.
> As you can see a part of the docstring says that it calls seq on its argument, meaning that the argument is expected sequeable (implement ISeq).

Because of that, I (blindly) thought that I could use a vector of vectors as a Matrix without any pennalty. 

I hope it helps

**Comment by mikera** [comment]
Hi @carocad 

`get-row` returns a row according to the format of the source matrix. That is why you get Clojure vectors if you call it on a vector of vectors. On the other hand, you will get Vectorz `AVector`s from `get-row` if you call it on a Vectorz matrix. 

That is why I am suggesting coercing to AMatrix first, since the get-row operation will then be much faster than building Clojure vectors.

Another option would be to use `rows` to get all the rows of each matrix first, and index into these collections as needed, rather than calling `get-row` repeatedly.
