### ISSUE TITLE
Why is clojure.core.matrix/round calling Math/rint instead of Math/round?

### ISSUE THREAD

**Issue by ysmiraak** [mikera/core.matrix#285]
I'm using version "0.52.1", and this is a bit confusing for me. Is there any particular reason?

**Comment by mikera** [comment]
`rint` returns a double value, which is (usually) the desired behaviour rather than converting to an integer type.

**Comment by ysmiraak** [comment]
But `Math/round` and `Math/rint` behave differently not only in types but also in values:
`(Math/rint 0.5) => 0.0` while `(Math/round 0.5) => 1`
Which caused me some trouble when I used it with the sigmoid function, because I assumed it to behave like `Math/round`. I know `Math/round` is problematic because it does not take integers. But I was actually counting on `core.matrix` to do the conversion for me :-)
Anyways, wouldn't it be better to call it `rint`?
