### ISSUE TITLE
ndarray mmul fails when second argument is a scalar

### ISSUE THREAD

**Issue by mars0i** [mikera/core.matrix#287]
`mmul` produces an error when the first argument is an ndarray matrix and the second argument is a scalar.  This problem doesn't occur if the scalar is the first argument.   The problem also doesn't occur with persistent-vector, vectorz-clj, or clatrix implementations.  (aljabr doesn't yet handle scalar multipliers with matrices in either position.)  `emul` doesn't have the same problem.  

```
user=> (m/mmul 2 (m/matrix :ndarray [[1 2][3 4]]))
#object[clojure.core.matrix.impl.ndarray_object.NDArray 0x28096b81 "[[2 4] [6 8]]"]

user=> (m/mmul (m/matrix :ndarray [[1 2][3 4]]) 2)

ClassCastException clojure.core.matrix.impl.ndarray_object.NDArray cannot be cast to java.lang.Number  clojure.lang.Numbers.multiply (Numbers.java:148)

```

**Comment by mikera** [comment]
Fixed in latest master. Problem was with matrix-multiply trying to scale with 0D arrays rather than a scalar value.
