### ISSUE TITLE
Classcast exception on creating dataset with sequence of rows with one or more strings

### ISSUE THREAD

**Issue by shark8me** [mikera/core.matrix#289]
With version  [net.mikera/core.matrix "0.54.0"], I get a class cast exception when a dataset is created with
- a sequence of rows
- one or more cells having a string.

```
user=> (require '[clojure.core.matrix.dataset :as cd])
nil
user=> (require '[clojure.core.matrix :as cm])
nil
user=> (cm/set-current-implementation :vectorz)
:vectorz
user=> (cd/dataset [:a :b] '(["a" 2]["a" 4]))

ClassCastException java.lang.String cannot be cast to java.lang.Number  clojure.lang.RT.doubleCast (RT.java:1312)
```

Version of vectorz: [net.mikera/vectorz-clj "0.45.0"]
This doesn't occur when the implementation is _not_ set

```
user=> (require '[clojure.core.matrix.dataset :as cd])
nil
user=> (cd/dataset [:a :b] '(["a" 2]["a" 4]))
#dataset/dataset {:column-names [:a :b], :columns [["a" "a"] [2 4]], :shape [2 2]}
```

This error is also seen for :ndarray-double implementation

```
user=> (cm/set-current-implementation :ndarray-double)
:ndarray-double
user=> (cd/dataset [:a :b] '(["a" 2]["a" 4]))

ClassCastException java.lang.String cannot be cast to java.lang.Number  clojure.lang.RT.doubleCast (RT.java:1312)
```

**Comment by mikera** [comment]
Thanks for the report. Temp workaround is to use a vector rather than a list to specify the rows:

``` clojure
(cd/dataset [:a :b] [["a" 2]["a" 4]])
```

**Comment by mikera** [comment]
Traced problem to `mp/get-columns` when applied to sequences

**Comment by mikera** [comment]
Oddly the problem does not seem to appear in the latest snapshot version.

**Comment by dmarjenburgh** [comment]
Git bisect points to f0d1f55b2e819a0fd00be079ba702cb863f697cb when the problem disappeared for both ndarray-double and vectorz

**Comment by mikera** [comment]
Cool thanks for checking @dmarjenburgh ! Guess we can close this now

**Comment by shark8me** [comment]
This problem is still seen with when my project.clj has version of [net.mikera/core.matrix "0.55.0"] and [net.mikera/vectorz-clj "0.45.0"]

**Comment by dmarjenburgh** [comment]
@shark8me 
It should be in the next release. Version "0.55.0" was released on September 6, but the fix was made on September 12th
