### ISSUE TITLE
Default implementation of norm is squared

### ISSUE THREAD

**Issue by dmarjenburgh** [mikera/core.matrix#291]
``` clj
(clojure.core.matrix.linear/norm [2]) ;;=> 4 (but should be 2)
```

**Comment by dmarjenburgh** [comment]
I submitted a PR. It also fixes the infinity-norm, which did not take the max of the absolute values.

In this case, I think property based testing would be really useful. All norms need to satisfy nonnegativity, the triangle inequality, etc. It would have caught these cases.

**Comment by samestep** [comment]
Should this issue be closed?

**Comment by mikera** [comment]
Yup I think so!
