### ISSUE TITLE
matrix? returns true for subvectors with different number of elements

### ISSUE THREAD

**Issue by nblumoe** [mikera/core.matrix#306]
I wonder if the following is intended behaviour:

```
 (m/matrix? [[1 2] [1] [1 2 3]])
; => true
```

Is this really supposed to return true even though the "rows"  have different lengths? Is this then treated as a sparse matrix?

**Comment by nblumoe** [comment]
Ok, I checked which matrices are actually being created from such data:

```
 (m/matrix [[1 2] [1] [1 2 3]])
#vectorz/matrix [[1.0,2.0],
[1.0,0.0],
[3.0,0.0]]
```

So at least with vectory the missing elements are filled with zeros. Is this well defined behaviour across all implementations?

**Comment by mikera** [comment]
Hi @nblumoe nested vectors with different shapes / lengths are not a valid core.matrix array. 

For performance reasons, we don't currently check this in all cases (it would require checking every element of the array!) so you will get undefined behaviour if you use it with other core.matrix API functions. Sometimes it may work, but no guarantees so I don't recommend relying on this.

**Comment by mikera** [comment]
It might be worth doing the check explicitly in `matrix?` or `array?` however. I will have a think about this.

**Comment by nblumoe** [comment]
Ok thanks, good to know. As you said it might be worth considering a change and see how it would impact the library in a broader sense. Maybe the shape checking for children could be optional? If performance is an issue one might need to make such a tradeoff, otherwise it seems a bit unpleasant when `matrix?` returns true for invalid matrices.

Some context:
I ran into this while I was building validity checks for some imported CSV data that I am then processing with `core.matrix`. I was going trying to use `matrix?` for some specs but realised that it is not sufficient and I had to add a simple `(apply same-shape? matrix)`.

**Comment by mikera** [comment]
Just FYI, it is better to use `(apply same-shape? (slices matrix))` - there isn't always a guarantee that you can treat a matrix as a sequence (it works for vectorz, persistent vectors etc but not all core.matrix arrays)

I'm considering a `validate-shape` API function that will perform this check.

**Comment by nblumoe** [comment]
Thanks for the tipp! I guess there are a couple of places where I might have issues like that with the implementation potentially leaking through. Not sure how to prevent this other than learning the `core.matrix` API by hard or just deal with it once it becomes an issue. I was also wondering how much this might affect performance. But the latter I would deal with once I have implemented correctly what I need and then can do the profiling to find whatever is worth improving.

**Comment by Vaguery** [comment]
I'd like to second the request for a `validate-shape` function.

**Comment by mikera** [comment]
Added a `validate-shape` function to the API, will be in the next release (hopefully soon!)
