### ISSUE TITLE
magnitude-squared returning NaN for negative scalar

### ISSUE THREAD

**Issue by harold** [mikera/core.matrix#309]
```
cortex.loss> (m/magnitude-squared [-0.1])
0.010000000000000002
cortex.loss> (m/magnitude-squared -0.1)
NaN
```

Is this expected?

**Comment by harold** [comment]
@charlesg3, @cnuernber --- relevant to your interests.

**Comment by mikera** [comment]
It's documented currently as working only on vectors... could potentially be made more generic though. What's the use case?

**Comment by harold** [comment]
No real use case, hit this code path because of a shape fumble (accidental extra application of the `first` function).

We were just surprised to get back `NaN` (and it took a while to track back to this function, as per the usual with `NaN` error propagation).

In this case, where the square magnitude of a scalar is well defined, I'd just expect it to return the square of its input. If it's designed to only work with vectors, some sort of invalid-argument-exception would have also worked in our case (since it would have led more quickly to the original fumble).

Hope that helps. Thanks, as ever, for your time. 👍

**Comment by mikera** [comment]
Let me have a think. I agree an exception would be better than a NaN.

But there's also the possibility of making it a full N-dimensional function, one that works on matrices as well (i.e. computes magnitudes of rows, or maybe computes magnitude of all elements in the matrix)

**Comment by harold** [comment]
Interesting; definitely your call. I have no strong feelings. :)

**Comment by mikera** [comment]
I've gone for a N-dimensional approach which computes the magnitude of all elements. So it works as a Frobenius norm on matrices etc. Will be a fix in the next core.matrix release.
