### ISSUE TITLE
Unclear behaviour while using dataset/column

### ISSUE THREAD

**Issue by shark8me** [mikera/core.matrix#310]
The API /API description for using the dataset/column method is unclear, for the following edge case:

```
;column names are strings
 (-> (cd/dataset ["a" "b"] [[1 2] [3 4]])
      (cd/column  "a"))
;;returns [1 3]

;column names are integers
  (-> (cd/dataset [0 1] [[1 2] [3 4]])
      (cd/column  0))
;;returns [1 3]

;column names are integers not starting from 0
  (-> (cd/dataset [1 2] [[1 2] [3 4]])
      (cd/column  1))
  ;;returns [2 4], expected [1 3]
```

Perhaps the method documentation should clarify that if integers are passed as the column argument, it is a zero-based index.

**Comment by mikera** [comment]
Hmmm need to think about this one. I don't really like the idea of the code behaving differently based on the type of argument. Probably, it should always treat the argument as a name (so your 3rd example would be a bug)

**Comment by mikera** [comment]
Fixed so that it always looks up column labels. People wanting to access column by index should use `c.c.m/get-column` instead.
