### ISSUE TITLE
join-rows function transforms integers into doubles

### ISSUE THREAD

**Issue by Eleonore9** [mikera/core.matrix#311]
Version `net.mikera/core.matrix` "0.55.0"

Using `clojure.core.matrix.dataset/join-rows` on two datasets containing integers returns a dataset with doubles. See example below.

This issue seems to be linked to the use of the function `dataset-from-rows` at the last step of `join-rows`.

`historic-dataset`
```
| :year | :age | :population |
|-------+------+-------------|
|  2016 |    0 |           3 |
|  2016 |    1 |           0 |
|  2016 |    2 |           1 |
```

`projection-dataset`
```
| :year | :age | :population |
|-------+------+-------------|
|  2017 |    0 |           2 |
|  2017 |    1 |           5 |
|  2018 |    0 |           1 |
|  2018 |    1 |           3 |
|  2019 |    0 |           2 |
|  2019 |    1 |           3 |
```

`(clojure.core.matrix.dataset/join-rows historic-dataset projection-dataset)`
```
|  :year | :age | :population |
|--------+------+-------------|
| 2016.0 |  0.0 |         3.0 |
| 2016.0 |  1.0 |         0.0 |
| 2016.0 |  2.0 |         1.0 |
| 2017.0 |  0.0 |         2.0 |
| 2017.0 |  1.0 |         5.0 |
| 2018.0 |  0.0 |         1.0 |
| 2018.0 |  1.0 |         3.0 |
| 2019.0 |  0.0 |         2.0 |
| 2019.0 |  1.0 |         3.0 |
```

**Comment by mikera** [comment]
Hmmm yes this seems not ideal. Better strategy would be to concatenate the column vectors one by one I think... will take a look at this for the next release

**Comment by Eleonore9** [comment]
We ended up doing something like
```Clojure
(-> historic-dataset 
      ds/row-maps
      (concat (ds/row-maps projection-dataset))
      ds/dataset)
```
Thanks for looking into it!

**Comment by mikera** [comment]
Added a fix for this in the latest master. Now joins the columns according to the implementation type of each column, which should avoid doing any coercion when using persistent vectors
