### ISSUE TITLE
pm breaks on dataset unless given :column-names? false

### ISSUE THREAD

**Issue by jsa-aerial** [mikera/core.matrix#317]
Don't know when it broke, but in current release 0.60.2:

(def d (ds/dataset [:A :B] [[1.0 2.0] [3.0 4.0]]))
#'expl/d
expl> (m/pm d)
ClassCastException java.lang.String cannot be cast to java.lang.Number  clojure.lang.Numbers.double_array (Numbers.java:1161)
expl> (m/pm d {:column-names? false})
[[1.000 2.000]
 [3.000 4.000]]

**Comment by mikera** [comment]
This happens for me when using the :double-array implementation only.

I have a fix for this, will release shortly

**Comment by mikera** [comment]
Fixed in `0.60.3`
