### ISSUE TITLE
TODO: Not yet implemented: for class clojure.lang.PersistentVector

### ISSUE THREAD

**Issue by lucasemmoreira** [mikera/core.matrix#338]
Hi there, 

I have been trying to use some functionalities from clojure.core.matrix.linear, although with no luck.

When I call: 

`user> (clojure.core.matrix.linear/lu [[1 -1] [1 1]])`

I get the error 

```
Execution error (ExceptionInfo) at clojure.core.matrix.impl.defaults/eval10432$fn (defaults.cljc:2618).
TODO: Not yet implemented: (mp/lu m options) for class clojure.lang.PersistentVector
```
This has happened with any function inside clojure.core.matrix.linear.

I am a very clojure beginner, but I think I have managed to correctly "import" matrix lib. I did like so:

```
(ns example.core
  (:require [clojure.core.matrix :as m]
            [clojure.core.matrix.linear :as lin])
  (:gen-class))

```
Antecipated apologies if this issue should not have been open here.

Thx!

**Comment by lucasemmoreira** [comment]
I figured it out...

Similarly to a similar to this issue [https://github.com/mikera/core.matrix/issues/322](url), all I had to do was to change the implementation. 

So I included in the project.clj file `[net.mikera/vectorz-clj "0.48.0"]` and called `(set-current-implementation :vectorz)`.

After that, I was able to call the functions in clojure.core.matrix.linear

I apologize for opening this issue unnecessarly.

**Comment by mikera** [comment]
OK glad you worked it out! Another helpful trick, if you don't want to change the current implementation (which is global, so use with care!) is to coerce the first argument to the implementation that you want, e.g.

```clojure
(clojure.core.matrix.linear/lu (array :vectorz [[1 -1] [1 1]]))
```

This ensures that the `core.matrix` protocols operate on the correct implementation.
