### ISSUE TITLE
unable to connect to project via lein

### ISSUE THREAD

**Issue by grtlr** [mikera/core.matrix#34]
I'm unable to connect to the _matrix-api_ project via lein. I've updated my local repository, as well as lein.

When I do `lein check` I get the following error:

```
Exception in thread "main" java.io.FileNotFoundException: Could not locate clojure/core/matrix/compliance_tester__init.class or clojure/core/matrix/compliance_tester.clj on classpath: 
```

When I connect to the project in the _repl_ with `lein repl` (in the project root) and try to use `clojure.core.matrix` this is what happens:

```
user=> (use 'clojure.core.matrix)
FileNotFoundException Could not locate clojure/core/matrix__init.class or clojure/core/matrix.clj on classpath:   clojure.lang.RT.load (RT.java:432)
```

Maybe the problem is that the files are located in `src/main/clojure/clojure/core/matrix` rather than `src/main/clojure/core/matrix`?

**Comment by mikera** [comment]
I'm not a lein user (since it is much easier to use Maven directly with Eclipse / Counterclockwise) so can't help you with the lein related questions.

However I can confirm that the correct source location is `src/main/clojure/clojure/core/matrix.clj`

Clojure appears twice, first because it is part of the source path `src/main/clojure` and then because the namespace name is `clojure.core.matrix`

**Comment by mikera** [comment]
Perhaps the project.clj should contain the following in order to recognise the Maven directory layout:

`:source-paths ["src/main/clojure"]`

Can anyone who knows both lein and Maven confirm this?

**Comment by grtlr** [comment]
Your last commit fixed this issue for me. Thank you very much. Unfortunately I don't have enough experience with Maven and lein to confirm that this is a valid and complete project setup. Maybe someone else has more experience with this?

**Comment by Velrok** [comment]
Could you paste your `project.clj` or put it in a gist and link it?

**Comment by mikera** [comment]
@Velrok are you after my project.clj? Latest version is in the develop branch: 

https://github.com/mikera/matrix-api/blob/develop/project.clj

I don't usually used Leiningen though, so could have plenty wrong with it: the Maven pom.xml is the single source of truth at the moment.

**Comment by Velrok** [comment]
Because I was negotiating with myself if I want to extent [vectorz-clj](https://github.com/mikera/vectorz-clj) and I confused the projects here for a moment :) .

**Comment by eigenhombre** [comment]
I also had this problem:
https://gist.github.com/eigenhombre/5230418

**Comment by eigenhombre** [comment]
Changing to develop branch fixed this for me as well.
What will be needed to get master working?  I would assume merging changes into project.clj.
I could set up a PR for that, but want to check first to get your thoughts (perhaps you plan to merge develop into master very soon).

**Comment by grtlr** [comment]
I think it would be a good idea to merge this change into the master branch. I think it would help to avoid further confusion.

**Comment by mikera** [comment]
I've pushed a 0.4.1 release out that contains this fix - hopefully makes it easier for everyone! Let me now if it works.....

**Comment by eigenhombre** [comment]
Works, thanks!
