### ISSUE TITLE
Mechanism to load matrix implementations

### ISSUE THREAD

**Issue by mikera** [mikera/core.matrix#4]
We could give users an easy way to load a specific matrix implementation.

I'm thinking something like:

``` clojure
(use 'core.matrix)

(use-matrix-implementation :jblas)
```

Mechanism would need to do a few things:
- look up the implementation in a list of known implementations
- `require` the implementation to ensure it is loaded. In case of failure, do something sane (e.g. give some instructions on how to get the dependency on the classpath)
- possibly "hook" into some core.matrix functions, e.g. functions to construct new matrices should produce JBLAS matrices by default

**Comment by mjwillson** [comment]
I wonder to what extent this needs automating, as opposed to just getting the user to (e.g.):

```
(:require [their.preferred.implementation :refer [matrix]])
```

Are there any other cases beyond the initial construction where the default matrix type produced could and should be customisable? For operations creating a matrix from existing matrices I'd imagine the result type would need to stay implementation-dependent (with most implementations producing output of the same type as the input). Perhaps the precedence of any available fallback coercion rules?

**Comment by mikera** [comment]
Clearly the user could set most of this up manually if they wanted to: but I think it's a big convenience to automatic it. There might be a few construction functions available and it would be a pain for users to ave to explicitly import them all:
- matrix
- diagonal-matrix
- zero-matrix (synonym for matrix?)
- scalar-matrix
- identity-matrix
- etc..

I can see the same mechanism also being useful also for things like explicit conversions, e.g. 

``` clojure
(clone some-arbitrary-matrix :jblas)
```

**Comment by mikera** [comment]
Closing this issue as the matrix loading / construction implementation now seems to be working fine in master
