### ISSUE TITLE
Add elementary row operations

### ISSUE THREAD

**Issue by mikera** [mikera/core.matrix#40]
Add the elementary row operations. (switching, multiplication, and row addition; see http://en.wikipedia.org/wiki/Elementary_matrix).

**Comment by si14** [comment]
I wondering why it is useful as a separate API function? Because of efficiency reasons?

**Comment by mikera** [comment]
There is probably an efficiency argument that could be made.

But I think the main point is that these operations are quite commonly used in matrix algorithms, so it makes sense to support them as API functions. The core.matrix API should ideally support most common/useful operations on matrices, and I believe the elementary row operations are in this category.

**Comment by si14** [comment]
I've clarified my point here: https://github.com/mikera/matrix-api/issues/39#issuecomment-19512608

**Comment by mikera** [comment]
We have a partial PR here: https://github.com/mikera/matrix-api/pull/41

**Comment by mikera** [comment]
Think this is now complete?
