### ISSUE TITLE
Broken emap for NDArray?

### ISSUE THREAD

**Issue by mikera** [mikera/core.matrix#51]
`emap` appears to incorrectly iterate too deep when an NDArray contains Clojure vectors, e.g.

``` clojure
(def m (new-array :ndarray [3 3])) ;; create a 3x3 NDarray
(def my-vectors (for [i (range 9)] [i (inc i)])) ;; a sequence of 9 vectors
(assign-array! m (object-array my-vectors)) ;; assign all the elements using an array

(emap count m) ;; should apply count to each of the 9 vectors
UnsupportedOperationException count not supported on this type: Long  clojure.lang.RT.countFrom (RT.java:545)
```

This could be a problem of NDArray depending on the persistent vector implementation, for which nested vectors are a known limitation?

**Comment by si14** [comment]
Yes, it's caused by using persistent vector's implementation of emap as a default (persistent vectors can't differentiate vectors as elements from vectors as dimensions). I'll fix default implementation or implement a protocol in NDArray, not sure yet what's better/easier.

**Comment by si14** [comment]
I've reimplemented default emap and added a test for it in ndarray tests. The test almost duplicates your counterexample and it is passed by current develop.

**Comment by si14** [comment]
The build errored due to forced push (rewording commit msg), sorry for Travis spam.

**Comment by mikera** [comment]
seems to be fixed so closing this one - thanks!
