### ISSUE TITLE
Add set-0d to PZeroDimensionAccess

### ISSUE THREAD

**Issue by si14** [mikera/core.matrix#54]
I think we should add add-0d (non-mutative one) to PZeroDimensionAccess for consistency.

**Comment by mikera** [comment]
It's an odd one: arguably it isn't needed since set-0d can just return the scalar value it is passed.... see the 1-arity implementation for clojure.core.matrix/mset for example.

Fine to add it though for completeness sake, we may find a use for it in the future.

**Comment by mikera** [comment]
Fixed here: https://github.com/mikera/matrix-api/commit/bb9250e88910428dd5c2e5540992e7a069424e53
