### ISSUE TITLE
Normalise benchmarks to per-operation timing

### ISSUE THREAD

**Issue by mikera** [mikera/core.matrix#59]
New benchmarks look good Dmitry!

I think it would be an improvement if the benchmarks normalised the results by deviding by the number of operations performed, so that the result is a per-operation timing. This would let us know precisely how many nanoseconds each operation is taking.

**Comment by si14** [comment]
I believe that this is already done by criterium for us.

**Comment by mikera** [comment]
Hmmmm...... If that's the case then I'm suspicious about the numbers in the latest bench.html

`get-1d` for example should not be taking 250ns, it should be more like 15-20ns.

Are you sure then benchmark code is working correctly? It looks to me like you are benchmarking `(apply f args)` which would be including the (lazy) construction of the test data in the benchmark, and also the cost of `apply` which is quite expensive (compared to the simple matrix operations at least).

**Comment by si14** [comment]
You are right, seems to be the case.

**Comment by si14** [comment]
Appears to be fixed: http://mikera.github.io/matrix-api/bench.html

**Comment by mikera** [comment]
Those numbers look a lot better!
