### ISSUE TITLE
Matrix division fails on 0.10

### ISSUE THREAD

**Issue by John-Poplett** [mikera/core.matrix#73]
I encountered this exception on matrix division while trying out 0.10. I do not see this problem on 0.9. The repl session in the screenshot below defines a 3x3 matrix and then divides it by itself to demonstrate the issue:

![image](https://f.cloud.github.com/assets/1044796/1321436/ffe9552c-33c2-11e3-841c-80cbf9cee799.png)

The exception I get is the following:

java.lang.ClassCastException: clojure.core.matrix.impl.ndarray.NDArray cannot be cast to java.lang.Number

John

**Comment by mikera** [comment]
Confirmed - seems to be a big in NDArray assuming that the second argument is a scalar number (when it could be any shape-compatible array)

It works fine for regular persistent vectors:

``` clojure
(def X [[1 2] [3 4]])
(div X X)
=> [[1 1] [1 1]]
```

@si14 are you able to take a look and fix this one? I get the suspicion that it may affect some other functions in NDArray too

**Comment by tgoossens** [comment]
Its probably just me. But as far as I know the matrix division is not defined like that. Because matrix multiplication is not commutative.

There is no way to know whether  A/B
 means B^-1 \* A or A \* B^-1 unless a convention is made which I would strongly dislike.

**Comment by mikera** [comment]
@tgoossens - I agree with you that matrices can't be easily divided for the reason that you describe.

However we're talking about a slightly different operation here - `div` is for element-wise division. So I think it is reasonably well defined as "elements of a divided by corresponding elements of b"
(with broadcasting as necessary to make the array sizes conformant).

**Comment by tgoossens** [comment]
My bad. Should have read the documentation better.

**Comment by mikera** [comment]
This is fixed I think by this commit:
https://github.com/mikera/core.matrix/commit/e5c7d0afeb1a0afd324109770cf256c1ecf0c34a
