### ISSUE TITLE
Surprising/inconsistent behavior of "matrix" on incorrect input

### ISSUE THREAD

**Issue by si14** [mikera/core.matrix#77]
``` clojure
linprog.core> (m/matrix :persistent-vector [[0.0 1.0 -1.0] [0.0 -1.0 0.0] [-1.0 0.0 -2.0] [-2.0 -1.0 0.0] [1 1 1 1]])
[[0.0 1.0 -1.0] [0.0 -1.0 0.0] [-1.0 0.0 -2.0] [-2.0 -1.0 0.0] [1 1 1 1]]
linprog.core> (m/matrix :vectorz [[0.0 1.0 -1.0] [0.0 -1.0 0.0] [-1.0 0.0 -2.0] [-2.0 -1.0 0.0] [1 1 1 1]])
nil
linprog.core> (m/matrix :ndarray [[0.0 1.0 -1.0] [0.0 -1.0 0.0] [-1.0 0.0 -2.0] [-2.0 -1.0 0.0] [1 1 1 1]])
#<NDArray [[0.0 1.0 -1.0] [0.0 -1.0 0.0] [-1.0 0.0 -2.0] [-2.0 -1.0 0.0] [1 1 1]]>
```

**Comment by mikera** [comment]
Thanks for the report Dmitry!

I think this should be an error in all cases?

We should probably allow protocol implementations for `mp/construct-matrix` to return nil if faced with a shape they don't support, which would allow a fall-back to an alternative implementation.

**Comment by mikera** [comment]
Fixed in this commit I think:
https://github.com/mikera/core.matrix/commit/fc50e4ac39743a1b46b7d402026994a42c15bfcb

**Comment by si14** [comment]
Yeah, seems that the error will be better in all cases. Thank you!
