### ISSUE TITLE
Add div! function

### ISSUE THREAD

**Issue by matthewrfellows** [mikera/core.matrix#78]
I can't seem to find the mutable version of div (i.e., div!).

Is this an oversight?

Thanks

(great project, by the way!)

**Comment by mikera** [comment]
Hi there, glad you like the project!

`div!` hasn't been added yet but I agree it should be there. All the major arithmetic functions should have equivalent mutable and immutable functions (heading towards 1.0)

We should aim to add this is an upcoming release.

**Comment by mikera** [comment]
Latest snapshot now has a `div!` API function, however this still needs a protocol and decent default implementations. Leaving this ticket open pending completion of this implementation. 

If anyone wants to have a crack at completing this, it's a good way to learn about how the core.matrix protocols work.

**Comment by mikera** [comment]
Closing this as I think it is now complete (thanks Tim for the patches!)
