### ISSUE TITLE
problem with one of the submatrix methods

### ISSUE THREAD

**Issue by rogerallen** [mikera/core.matrix#79]
Found an issue by inspection.  Notice that the last call to `mp/submatrix` here
https://github.com/mikera/core.matrix/blob/develop/src/main/clojure/clojure/core/matrix.clj#L611
(and below) does not use the `m` input variable.  

```
(defn submatrix
  "Gets a view of a submatrix, for a set of index ranges.
   Index ranges should be [start, length] pairs.
   Index range pairs can be nil (gets the whole range) "
  ([m index-ranges]
    (mp/submatrix m index-ranges))
  ([m dimension index-range]
    (mp/submatrix m (assoc (vec (repeat (mp/dimensionality m) nil)) dimension index-range)))
  ([m row-start row-length col-start col-length]
    (mp/submatrix (list row-start row-length) (list col-start col-length))))
```

**Comment by mikera** [comment]
Thanks for the report! Agreed, can't see how that could possibly work......

Fix here:
e9ae30f28c6611f90fdfcf37c7039f8042eefce2
