### ISSUE TITLE
Race condition in loading implementation

### ISSUE THREAD

**Issue by yongqli** [mikera/core.matrix#80]
% lein repl
...
user=> (use 'clojure.core.matrix)
nil
user=> (matrix :clatrix [0 1])
(0.0 1.0)
user=> Bye for now!%

 % lein repl
...
user=> (use 'clojure.core.matrix)
nil
user=> `(doall (map deref (for [i (range 10)]  (future (matrix :clatrix [0 1])))))`
RuntimeException Unable to find implementation: [:clatrix]  clojure.core.matrix.implementations/get-canonical-object (implementations.clj:76)

user=> Bye for now!%

**Comment by mikera** [comment]
Thanks for the report! I think what is happening is some sort of race with Clojure's code loading (since the use of the `:clatrix` keyword should trigger the loading of the clatrix implementation namespace. I'll take a look into this.

**Comment by mikera** [comment]
I think that this might be a Clatrix bug rather than core.matriix. At least, I haven't been able to reproduce with other implementations.

**Comment by mikera** [comment]
Closed since this appears to be a Clatrix only issue
