### ISSUE TITLE
pow: Adding support for array exponents

### ISSUE THREAD

**Issue by luxbock** [mikera/core.matrix#86]
At the moment `pow` only works when the exponent is a scalar. I'm a little bit out of depth with trying to contribute, but the following:

``` clojure
(extend-protocol mp/PExponent
  Number
    (element-pow [m exponent]
      (if (array? exponent)
        (mp/element-map exponent #(Math/pow (.doubleValue m) (.doubleValue ^Number %)))
        (Math/pow (.doubleValue m) (double exponent))))
  Object
    (element-pow [m exponent]
      (if (array? exponent)
        (mp/element-map m #(Math/pow (.doubleValue ^Number %1) (.doubleValue ^Number %2)) exponent)
        (mp/element-map m #(Math/pow (.doubleValue ^Number %) exponent)))))
```

... appears to work for persistent vectors, i.e.:

``` clojure
clojure.core.matrix> (pow (matrix :persistent-vector [[1 2 3] [5 6 7]])
                          (matrix :persistent-vector [[2 2 2] [2 2 2]]))
[[1.0 4.0 9.0] [25.0 36.0 49.0]]
```

The only other implementation I tried out was vectorz-clj, where it works when the base is a scalar, but fails with:

`VectorzException 0D get not supported on matrix!  mikera.matrixx.AMatrix.get (AMatrix.java:82)`

when both the base and the exponent are matrices.

Is there something more I can do this to work more broadly? Should I submit this for a pull request?

**Comment by mikera** [comment]
This is a good idea - I agree pow would be better if it works for arbitrary arrays. It allows nice things like using arrays for representing power series, etc.

I'd be happy to accept PRs on this one. It may take a few changes to get the full support in place, but I think we can do it bit-by-bit

Note that we haven't yet explicitly defined whether `element-map` should support broadcasting or not. I think the right answer is yes (in which case your solution works) but if not then we would need to add in some explicit broadcasting steps.

vectorz-clj currently assumes the exponent is a number, this would need fixing separately after we update core.matrix

**Comment by mikera** [comment]
Think this is all good - closing as complete
