### ISSUE TITLE
Inplace operator?

### ISSUE THREAD

**Issue by demon386** [mikera/core.matrix#88]
Inplace operations, like +=, -=, *=, /= are quite common in scientific computing.

Seems that these operators are still lacking?

**Comment by mikera** [comment]
Good idea, I think these make sense for the mutable matrix implementations.

They probably should be in `clojure.core.matrix.operators` namespace (alongside the current operators), and delegate to the appropriate mutable protocol. Effectively, they would be synonyms for `add!`, `sub!`, `mul!` etc.

**Comment by mikera** [comment]
These are now in the latest `core.matrix` 0.21.0
