### ISSUE TITLE
mset problems when using the vectorz implementation

### ISSUE THREAD

**Issue by lilian0312** [mikera/core.matrix#90]
;; Here is the bug when using vectorz:
(set-current-implementation :vectorz)
(def mmm (zero-array [4 4]))
(= mmm (mset mmm 0 2 99.3))
;; => true
;; i.e. mset seems to return the old matrix unchanged, while it says in its docs that
;; it will return the new matrix with the changed value.

**Comment by mikera** [comment]
Thanks! confirmed that I can reproduce this bug. 

I'll do a new release with a fix shortly.

**Comment by mikera** [comment]
Note: this is a actually defect in the vectorz-clj implementation, not core.matrix

**Comment by mikera** [comment]
OK I pushed a version 0.17.1 of vectorz-clj which should fix this issue. Let me know if this doesn't solve your problem!

**Comment by lilian0312** [comment]
that was quick! :-)) 
solved the problem, thanks.

**Comment by mikera** [comment]
It was a one-character fix: closing parenthesis in the wrong place :-)
