### ISSUE TITLE
large ndarray-double matrices

### ISSUE THREAD

**Issue by akhudek** [mikera/core.matrix#91]
It seems that it is impossible to allocate and use a very large ndarray-double matrix.

(set-current-implementation :ndarray-double)

(time (def a (new-array [1 (apply \* (repeat 24 2))])))
"Elapsed time: 11262.558 msecs"

(time (def a\* (emap! (fn [e](- 1.0 %28rand 2%29)) a)))
;; never returns, or at least not in any time that I'm willing to wait

It works fine with other implementations. E.g.

(set-current-implementation :vectorz)

(time (def a (new-array [1 (apply \* (repeat 24 2))])))
"Elapsed time: 849.742 msecs"

(time (def a\* (emap! (fn [e](- 1.0 %28rand 2%29)) a)))
"Elapsed time: 813.77 msecs"

[On an unrelated note, I'm getting numerical accuracy problems with vectorz compared to straight persistent vectors or double-arrays.]

**Comment by mikera** [comment]
Thanks for the report! 

Can you file separate issue against Vectorz here: (https://github.com/mikera/vectorz/issues?state=open) with relation to the numerical accuracy issues you mention?

(if it is just that the numerical results differ slightly between implementations: this is expected - we don't specify the order of computations in core.matrix itself so it's possible for different floating point rounding to occur).

**Comment by mikera** [comment]
I think this issue is fixed in the latest branch (at least, the operations complete in sensible time for NDArray.... there are probably still more optimisations that could be done)

Should be resolved in 0.21.0

**Comment by mikera** [comment]
Closing this as I think it is fixed in `0.21.0`
